/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.9
 * Generated at: 2024-07-19 08:16:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class ClaimsEntry_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("  <title>Admission</title>\r\n");
      out.write("</head>\r\n");

   String mode=request.getParameter("mode");
   String code=request.getParameter("code");
   String userId=(String)session.getAttribute("LOGIN_ID");
   String branch=request.getParameter("branch");
   String rptId=request.getParameter("id");

      out.write("\r\n");
      out.write("<body>	\r\n");
      out.write("\r\n");
      out.write("	<div class=\"card border-0 shadow\">\r\n");
      out.write("		<div class=\"card-body lpage\">\r\n");
      out.write("			<div class=\"row w-100\">\r\n");
      out.write("				<div class=\"col-md-6 d-flex align-items-center\">\r\n");
      out.write("					<h4 class=\"header-title\">Claims</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div  class=\"col-md-6\" id=\"addGrp\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-md-7 d-flex text-right\">\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<span class=\"input-group-text\">From</span>\r\n");
      out.write("								<input id=\"fromDate\" name=\"fromDate\" inputType=\"date\"  type=\"text\" mandatory=\"1\"  class=\"form-control\"/>\r\n");
      out.write("								<span class=\"input-group-text\">To</span>\r\n");
      out.write("								<input id=\"toDate\" name=\"toDate\" inputType=\"date\"  type=\"text\" mandatory=\"1\"  class=\"form-control\"/> &ensp;\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-edit\" onclick=\"reportGo('");
      out.print(rptId);
      out.write("')\">Go</button> &ensp;\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-5\" style=\"text-align: right;\">\r\n");
      out.write("							<button type=\"button\" class=\"btn btn-clear\" onclick='toggleHeaderRow()'><span class=\"mdi mdi-filter-variant\">Search</span></button>	\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row \" id=\"jqcontainer\" >\r\n");
      out.write("			  <div class=\"table-container\" >\r\n");
      out.write("				 <div id=\"xyz\" class=\"w-100\"></div>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>	\r\n");
      out.write("			<div id=\"callback\" class=\"row \" style=\"display:none;\">\r\n");
      out.write("				<div class=\"col-md-12 col-sm-12 marLfBx panelOrange hcH\">\r\n");
      out.write("					<div class=\"col-md-12 col-sm-12 mpZero\">\r\n");
      out.write("					<div class=\"col-md-12 col-sm-12 mpZero\">\r\n");
      out.write("					 <div  class=\"col-md-12 col-sm-12 mpZero\">		\r\n");
      out.write("					 <div class=\"form-group mbotto\">\r\n");
      out.write("						 <div class=\"col-md-2\"><label>Corporate Name</label></div>\r\n");
      out.write("						 <div class=\"col-md-10\"><input type=\"text\" class=\"form-control\" id=\"corporatename\"><input type=\"hidden\" class=\"form-control\" id=\"corporatecode\"><input type=\"hidden\" class=\"form-control\" id=\"claimcode\"></div>\r\n");
      out.write("					 </div>\r\n");
      out.write("					 </div>	\r\n");
      out.write("				 </div>\r\n");
      out.write("				 <div class=\"clearfix\"></div>	\r\n");
      out.write("				 <div class=\"col-md-12 col-sm-12 mpZero\">\r\n");
      out.write("					 <div class=\"form-group mbotto\">\r\n");
      out.write("					 <div class=\"col-md-2\"><label>Claim Amount</label></div>\r\n");
      out.write("					 <div class=\"col-md-10\"><input type=\"text\" class=\"form-control\" id=\"claimamount\"><input type=\"hidden\" id=\"claimdate\"/></div>\r\n");
      out.write("					 </div>\r\n");
      out.write("				 </div>\r\n");
      out.write("				 <div class=\"clearfix\"></div> \r\n");
      out.write("				 <div class=\"col-md-12 col-sm-12 mpZero\">\r\n");
      out.write("					 <div  class=\"col-md-6 col-sm-6 mpZero\" style=\"display:block\">		\r\n");
      out.write("					 <div class=\"form-group mbotto\">\r\n");
      out.write("						 <div class=\"col-md-4\"><label>TDS Amount</label></div>\r\n");
      out.write("						 <div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"tdsamount\"></div>\r\n");
      out.write("					 </div>\r\n");
      out.write("					 </div>	\r\n");
      out.write("					 <div  class=\"col-md-6 col-sm-6 mpZero\" style=\"display:block\">		\r\n");
      out.write("					 <div class=\"form-group mbotto\">\r\n");
      out.write("						 <div class=\"col-md-4\"><label>Mischellenous Amount</label></div>\r\n");
      out.write("						 <div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"mischamount\"></div>\r\n");
      out.write("					 </div>\r\n");
      out.write("					 </div>\r\n");
      out.write("				 </div>\r\n");
      out.write("				 \r\n");
      out.write("				 <div class=\"clearfix\"></div>	\r\n");
      out.write("				 <div class=\"col-md-12 col-sm-12 mpZero\">\r\n");
      out.write("					 <div  class=\"col-md-6 col-sm-6 mpZero\">		\r\n");
      out.write("					 <div class=\"form-group mbotto\">\r\n");
      out.write("						 <div class=\"col-md-4\"><label>Cheque No</label></div>\r\n");
      out.write("						 <div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"chequeno\"></div>\r\n");
      out.write("					 </div>\r\n");
      out.write("					 </div>	\r\n");
      out.write("					 <div  class=\"col-md-6 col-sm-6 mpZero\">		\r\n");
      out.write("					 <div class=\"form-group mbotto\">\r\n");
      out.write("						 <div class=\"col-md-4\"><label>Cheque Date</label></div>\r\n");
      out.write("						 <div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"chequedate\"></div>\r\n");
      out.write("					 </div>\r\n");
      out.write("					 </div>\r\n");
      out.write("				 </div>\r\n");
      out.write("				 <div class=\"clearfix\"></div>	\r\n");
      out.write("				 <div class=\"col-md-12 col-sm-12 mpZero\">\r\n");
      out.write("					 <div  class=\"col-md-6 col-sm-6 mpZero\">		\r\n");
      out.write("					 <div class=\"form-group mbotto\">\r\n");
      out.write("						 <div class=\"col-md-4\"><label>Cheque Bank Name</label></div>\r\n");
      out.write("						 <div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"bankname\"></div>\r\n");
      out.write("					 </div>\r\n");
      out.write("					 </div>	\r\n");
      out.write("					 <div  class=\"col-md-6 col-sm-6 mpZero\">		\r\n");
      out.write("					 <div class=\"form-group mbotto\">\r\n");
      out.write("						 <div class=\"col-md-4\"><label>Deposited Bank</label></div>\r\n");
      out.write("						 <div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"depbankname\"><input type=\"hidden\" id=\"depbankcode\"/></div>\r\n");
      out.write("					 </div>\r\n");
      out.write("					 </div>\r\n");
      out.write("				 </div>\r\n");
      out.write("			  </div>\r\n");
      out.write("			 </div>\r\n");
      out.write("			 <div class=\"clearfix\"></div>	\r\n");
      out.write("			  <div class=\"col-md-12 col-sm-12 marLfBx panelOrange hcH\">\r\n");
      out.write("					<div class=\"col-md-12 col-sm-12 mpZero\" id=\"claimgrid\" style=\"height:300px\">\r\n");
      out.write("			   </div>\r\n");
      out.write("			 </div>\r\n");
      out.write("			 <div class=\"clearfix\"></div>	\r\n");
      out.write("			  <div class=\"col-md-12 col-sm-12 mpZero\">\r\n");
      out.write("					<div class=\"col-md-12 col-sm-12 mpZero\">\r\n");
      out.write("						<div class=\"col-md-6 text-center mpZero\">\r\n");
      out.write("							<div style=\"background:#fedc34; display:inline-block; width:100%; padding-top:5px;\" >\r\n");
      out.write("							 <div class=\"netAm\" id=\"netAmt\">Total Amount 0.00</div>\r\n");
      out.write("						 </div>\r\n");
      out.write("						 <div class=\"form-group mbotto\" style=\"display:none\">\r\n");
      out.write("							 <div class=\"col-md-4\"><label>Total</label></div>\r\n");
      out.write("							 <div class=\"col-md-8\"><label id=\"totalamt\"></label>\r\n");
      out.write("							 </div>						\r\n");
      out.write("						 </div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6 text-right mpZero\">\r\n");
      out.write("							<button id=\"btnClear\" class=\"btn btn-default\" type=\"button\" onclick=\"hideMasterData()\">Close</button>\r\n");
      out.write("							<button id=\"btnSave\" class=\"btn btn-default\" type=\"button\" onclick=\"saveBill()\">Save</button>\r\n");
      out.write("						</div>\r\n");
      out.write("				 </div>\r\n");
      out.write("			 </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	$('#fromDate').datepicker({\r\n");
      out.write("				 language: \"en\",\r\n");
      out.write("       			 autoclose: true,\r\n");
      out.write("       			 todayHighlight: true,\r\n");
      out.write("	 	 	     format:'dd/mm/yyyy'\r\n");
      out.write("	});\r\n");
      out.write("	if($('#fromDate').val()==\"\"){\r\n");
      out.write("		var cd=new Date();\r\n");
      out.write("		$('#fromDate').datepicker(\"setDate\",cd);\r\n");
      out.write("	}\r\n");
      out.write("	$('#todate').datepicker({\r\n");
      out.write("				 language: \"en\",\r\n");
      out.write("       			 autoclose: true,\r\n");
      out.write("       			 todayHighlight: true,\r\n");
      out.write("	 	 	     format:'dd/mm/yyyy'\r\n");
      out.write("	});			\r\n");
      out.write("	if($('#toDate').val()==\"\"){\r\n");
      out.write("		var cd=new Date();\r\n");
      out.write("		$('#toDate').datepicker(\"setDate\",cd);\r\n");
      out.write("	}	\r\n");
      out.write("	loadBranchData();\r\n");
      out.write("	jqReport(500011,\"#xyz\",\"&fromdate=\"+$('#fromDate').val()+\"&todate=\"+$('#toDate').val());\r\n");
      out.write("    var sProps={js:\"\",screen:[\r\n");
      out.write("  	{name:\"group1\",predesigned:true,contentType:\"Fields\",\r\n");
      out.write("  	fields:[\r\n");
      out.write("  	{name:\"claimcode\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"branchcode\"},\r\n");
      out.write("  	{name:\"branchcode\",inputType:0,type:\"INT\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"corporatename\"},\r\n");
      out.write("  	{name:\"corporatename\",inputType:0,type:\"LOV\",caption:\"\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":true,nf:\"claimamount\",lovOptions:{url:\"/waggle/service/ajax\",ajax:\"insurancecompany\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"corporatename\",tt:false,id:\"icm_name\"},{tgt:\"corporatename\",tt:true,id:\"icm_name\"},{tgt:\"corporatecode\",tt:false,id:\"icm_code\"}]}},\r\n");
      out.write("  	{name:\"corporatecode\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"claimamount\"},  	\r\n");
      out.write("  	{name:\"claimamount\",inputType:0,type:\"DECIMAL\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"tdsamount\"},\r\n");
      out.write("  	{name:\"tdsamount\",inputType:0,type:\"DECIMAL\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"mischamount\"},\r\n");
      out.write("  	{name:\"mischamount\",inputType:0,type:\"DECIMAL\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"chequeno\"},\r\n");
      out.write("  	{name:\"chequeno\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"chequedate\"},\r\n");
      out.write("  	{name:\"chequedate\",inputType:0,type:\"DATE\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"bankname\"},\r\n");
      out.write("  	{name:\"bankname\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":40,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"depbankname\"},\r\n");
      out.write("  	{name:\"depbankname\",inputType:0,type:\"LOV\",caption:\"\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"depbankcode\",lovOptions:{url:\"/waggle/service/ajax\",ajax:\"banks\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"depbankname\",tt:false,id:\"lm_name\"},{tgt:\"depbankname\",tt:true,id:\"lm_name\"},{tgt:\"depbankcode\",tt:false,id:\"lm_code\"}]}},\r\n");
      out.write("  	{name:\"depbankcode\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"btnSave\"},\r\n");
      out.write("  	{name:\"totalamt\",inputType:0,type:\"DECIMAL\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"btnSave\"},  	  	\r\n");
      out.write("  	{name:\"claimdate\",inputType:0,type:\"TDATE\",caption:\"\",mandatory:false,defaultValue:\"1\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"btnSave\"},  	\r\n");
      out.write("  	{name:\"btnSave\",inputType:3,caption:\"\",visible:false,readOnly:true},\r\n");
      out.write("    {name:\"btnClear\",inputType:3,caption:\"\",visible:false,readOnly:true}\r\n");
      out.write("  	]},\r\n");
      out.write("  	{name:\"claimgrid\",title:\"\",contentType:\"Table\",tableProperties:{rowObject:true,serialNumberColumn:\"sno\",rowEmptyCheckColumn:\"patienttypecode\",optional:false,columns:[\r\n");
      out.write("    {order:\"0\",id: \"sno\", name: \"SNo\", field: \"sno\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":true,\"chkTag\":false,width:50,sno:true},\r\n");
      out.write("    {order:\"1\",id: \"patienttypecode\", name: \"PatientType\", field: \"patienttypecode\",defaultValue:\"1\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":true,width:0,\"chkTag\":false},\r\n");
      out.write("    {order:\"2\",id: \"patienttype\", name: \"IP/OP\", field: \"patienttype\",defaultValue:\"\",\"inputType\":0,\"type\":\"LOV\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":true,width:0,\"chkTag\":true,lovOptions:{url:\"/waggle/service/ajax\",ajax:\"patienttype\",scrollEnabled:true,searchFromList:false,dsi:1,params:[],results:[\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:true,row:\"cr\",id:\"pt_shortname\",col:\"patienttype\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"pt_shortname\",col:\"patienttype\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"pt_code\",col:\"patienttypecode\"}\r\n");
      out.write("  	]},validation:\"validatePatientType\"\r\n");
      out.write("    },\r\n");
      out.write("    {order:\"3\",id: \"patientcode\", name: \"PatientCode\", field: \"patientcode\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:0,\"chkTag\":false},\r\n");
      out.write("    {order:\"4\",id: \"patientname\", name: \"Patient Name\", field: \"patientname\",defaultValue:\"0\",\"inputType\":0,\"type\":\"LOV\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":true,width:200,\"chkTag\":true,lovOptions:{url:\"/waggle/service/ajax\",ajax:\"inspatients\",scrollEnabled:true,searchFromList:false,dsi:1,params:[{n:\"corporate\",src:\"corporatecode\",tt:false},{n:\"searchtxt\",src:\"claimgrid_data\",row:\"cr\",col:\"patientname\",tt:false}],results:[\r\n");
      out.write("    {tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"patienttype\",col:\"patienttypecode\"},\r\n");
      out.write("    {tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"pt_shortname\",col:\"patienttype\"},\r\n");
      out.write("    {tgt:\"claimgrid_data\",tt:true,row:\"cr\",id:\"pt_shortname\",col:\"patienttype\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"pam_code\",col:\"patientcode\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"pam_no\",col:\"ipno\"},  	\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:true,row:\"cr\",id:\"pam_name\",col:\"patientname\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"pam_name\",col:\"patientname\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"pam_sponsor_approvalno\",col:\"claimno\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"dh_no\",col:\"billkey\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"dh_bill_no\",col:\"billno\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"dh_total_rent\",col:\"nursing\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"dh_total_lab\",col:\"invest\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"dh_total_pharmacy\",col:\"pharmacy\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"dh_profesional_charges\",col:\"professional\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"dh_total_amount\",col:\"totalamount\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"cp_approved_amount\",col:\"approvedamount\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"hospregcode\",col:\"hospregcode\"},\r\n");
      out.write("  	{tgt:\"claimgrid_data\",tt:false,row:\"cr\",id:\"claimno\",col:\"claimsno\"}\r\n");
      out.write("  	]}\r\n");
      out.write("  	},    \r\n");
      out.write("    {order:\"5\",id: \"claimno\", name: \"Claim No\", field: \"claimno\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":true,width:150,\"chkTag\":false},    \r\n");
      out.write("    {order:\"6\",id: \"ipno\", name: \"IP No\", field: \"ipno\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:100,\"chkTag\":false},\r\n");
      out.write("    {order:\"7\",id: \"billkey\", name: \"Bill Key\", field: \"billkey\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:0,\"chkTag\":false},\r\n");
      out.write("  	{order:\"8\",id: \"billno\", name: \"Bill No\", field: \"billno\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:0,\"chkTag\":false},\r\n");
      out.write("  	{order:\"9\",id: \"nursing\", name: \"Nursing\", field: \"nursing\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:150,align:\"right\"},\r\n");
      out.write("  	{order:\"10\",id: \"invest\", name: \"Investigation\", field: \"invest\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:150,align:\"right\"},\r\n");
      out.write("  	{order:\"11\",id: \"professional\", name: \"Professional\", field: \"professional\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:150,align:\"right\"},\r\n");
      out.write("  	{order:\"12\",id: \"pharmacy\", name: \"Pharmacy\", field: \"pharmacy\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:150,align:\"right\"},\r\n");
      out.write("  	{order:\"13\",id: \"totalamount\", name: \"Bill Amount\", field: \"totalamount\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":true,width:150,align:\"right\"},\r\n");
      out.write("  	{order:\"14\",id: \"approvedamount\", name: \"Approved Amount\", field: \"approvedamount\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":true,width:150,align:\"right\"},\r\n");
      out.write("  	{order:\"15\",id: \"approvalamount\", name: \"Claim Amount\", field: \"approvalamount\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":true,width:150,align:\"right\",onchange:\"onAppAmountChange\"},\r\n");
      out.write("  	{order:\"16\",id: \"pharmacyamount\", name: \"Pharmacy Share\", field: \"pharmacyamount\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:150,align:\"right\"},\r\n");
      out.write("  	{order:\"17\",id: \"nursingamount\", name: \"Nursing Share\", field: \"nursingamount\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:150,align:\"right\"},\r\n");
      out.write("  	{order:\"18\",id: \"doctoramount\", name: \"Doctor\", field: \"doctoramount\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:150,align:\"right\"},\r\n");
      out.write("  	{order:\"19\",id: \"hospregcode\", name: \"HospCode\", field: \"hospregcode\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,align:\"right\"}  	,\r\n");
      out.write("  	{order:\"20\",id: \"claimsno\", name: \"Claim No\", field: \"claimsno\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,align:\"right\"}\r\n");
      out.write("    ]\r\n");
      out.write("    }}]};\r\n");
      out.write("	var claims=new FlexUI.Screen(\"claims\",sProps);	\r\n");
      out.write("	var l=new FlexUI.Ajax();\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("            screenObjects.getScreenObject(\"branchcode\").setValue($('#branch').val());\r\n");
      out.write("            screenObjects.getScreenObject(\"claimgrid_data\").getInputField().onTextKeyDown.subscribe(tableTextKeyDown);\r\n");
      out.write("            screenObjects.getScreenObject(\"claimgrid_data\").onAfterDeleteRow.subscribe(tableRowDelete);\r\n");
      out.write("            $('#subtitle').text(\"\");\r\n");
      out.write("            $('#screentitle').text(\"Billing\");\r\n");
      out.write("            $('#btnSave').css(\"display\",\"inline-block\");\r\n");
      out.write("            loadActions(500011);\r\n");
      out.write("        });\r\n");
      out.write("        function saveBill(){\r\n");
      out.write("        	if(claims.getSaveInProgress()) return;\r\n");
      out.write("        	var r=null;\r\n");
      out.write("    		claims.setOperation(\"ADD\");\r\n");
      out.write("    		claims.setScreenCode(21);\r\n");
      out.write("    		var d=claims.processDataToSave();\r\n");
      out.write("    		claims.setSaveInProgress(true);    		\r\n");
      out.write("			if(\"FAILED\"!=d){\r\n");
      out.write("				var s=new FlexUI.Ajax();\r\n");
      out.write("				showLoader();\r\n");
      out.write("				r=s.callAjax(\"POST\",\"/waggle/service/screen/save\",d);\r\n");
      out.write("				hideLoader();\r\n");
      out.write("		 	}else{\r\n");
      out.write("		 		alert(\"Please correct the validation errors and continue...\");\r\n");
      out.write("		 		claims.setSaveInProgress(false);\r\n");
      out.write("		 		return;\r\n");
      out.write("		 	}		 \r\n");
      out.write("		 	if(r.result==\"Success\"){\r\n");
      out.write("				alert(r.message+\" [No:\"+r.code+\"]\");\r\n");
      out.write("				hideMasterData();\r\n");
      out.write("				return r.key;			\r\n");
      out.write("			}else{\r\n");
      out.write("				claims.setSaveInProgress(false);								\r\n");
      out.write("				alert(r.message);	\r\n");
      out.write("			}\r\n");
      out.write("        }\r\n");
      out.write("        function clearInnerScreen(){\r\n");
      out.write("        	claims.clearScreen();\r\n");
      out.write("        	claims.setSaveInProgress(false);        	\r\n");
      out.write("        	screenObjects.getScreenObject(\"branchcode\").setValue($('#branch').val());\r\n");
      out.write("        }\r\n");
      out.write("        function onAppAmountChange(id,me){\r\n");
      out.write("			var t=me.getParent();\r\n");
      out.write("			calculateAmount(t.getCurrentRow());\r\n");
      out.write("			calculateTotal();\r\n");
      out.write("			return true;\r\n");
      out.write("		}\r\n");
      out.write("		function calculateTotal(){\r\n");
      out.write("			var total=0;\r\n");
      out.write("			var t=screenObjects.getScreenObject(\"claimgrid_data\");\r\n");
      out.write("			var cols=t.getCols();\r\n");
      out.write("			var s=t.getSize();\r\n");
      out.write("			for(var i=0;i<s;i++){\r\n");
      out.write("				total+=toNumber(t.getText(i,cols.approvalamount));\r\n");
      out.write("			}\r\n");
      out.write("			screenObjects.getScreenObject(\"totalamt\").setValue(roundOff(total,2));\r\n");
      out.write("			$(\"#netAmt\").html(\"Total Amount   \"+roundOff(total,2));\r\n");
      out.write("		}\r\n");
      out.write("		function calculateAmount(row){\r\n");
      out.write("			var t=screenObjects.getScreenObject(\"claimgrid_data\");\r\n");
      out.write("			var cols=t.getCols();\r\n");
      out.write("			var pharmacyAmount=0;\r\n");
      out.write("			var nursingAmount=0;\r\n");
      out.write("			var professionalAmount=0;\r\n");
      out.write("			var nursing=toNumber(t.getText(row,cols.nursing))+toNumber(t.getText(row,cols.invest));\r\n");
      out.write("			var professional=toNumber(t.getText(row,cols.professional));\r\n");
      out.write("			var pharmacy=toNumber(t.getText(row,cols.pharmacy));\r\n");
      out.write("			var claimAmt=toNumber(t.getText(row,cols.totalamount));\r\n");
      out.write("			var appAmt=toNumber(t.getText(row,cols.approvalamount));\r\n");
      out.write("			if(t.getText(row,cols.patienttypecode)==\"1\"){\r\n");
      out.write("				if(appAmt>claimAmt){\r\n");
      out.write("					pharmacyAmount=pharmacy;\r\n");
      out.write("					appAmt=appAmt-pharmacy;\r\n");
      out.write("					professionalAmount=professional;\r\n");
      out.write("					appAmt=appAmt-professional;\r\n");
      out.write("					nursingAmount=appAmt;\r\n");
      out.write("				}else{\r\n");
      out.write("					if(appAmt>=pharmacy){\r\n");
      out.write("						pharmacyAmount=pharmacy;\r\n");
      out.write("						appAmt=appAmt-pharmacy;\r\n");
      out.write("					}else{\r\n");
      out.write("						pharmacyAmount=appAmt;\r\n");
      out.write("						appAmt=0;\r\n");
      out.write("					}\r\n");
      out.write("					if(appAmt>0){\r\n");
      out.write("						var nursingPerc=nursing/(claimAmt-pharmacy);\r\n");
      out.write("						nursingAmount=appAmt*nursingPerc;\r\n");
      out.write("						professionalAmount=appAmt-nursingAmount;\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				t.setText(row,cols.pharmacyamount,pharmacyAmount);\r\n");
      out.write("				t.setText(row,cols.nursingamount,nursingAmount);\r\n");
      out.write("				t.setText(row,cols.doctoramount,professionalAmount);\r\n");
      out.write("			}else{\r\n");
      out.write("				t.setText(row,cols.nursingamount,appAmt);\r\n");
      out.write("			}\r\n");
      out.write("			//calculate shares	\r\n");
      out.write("		}\r\n");
      out.write("		function tableTextKeyDown(e,args){\r\n");
      out.write("			var key=e.which || e.keyCode;\r\n");
      out.write("			if(key==113){\r\n");
      out.write("				saveBill();\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		function tableRowDelete(e,args){\r\n");
      out.write("			calculateTotal();\r\n");
      out.write("		}\r\n");
      out.write("		function preValidatePatientName(id,me,row,col){\r\n");
      out.write("			if(!claims.getSaveInProgress()){\r\n");
      out.write("				var t=screenObjects.getScreenObject(\"claimgrid_data\");\r\n");
      out.write("				var corporate=screenObjects.getScreenObject(\"corporatecode\").getValue();\r\n");
      out.write("				var cols=t.getCols();\r\n");
      out.write("				var sTxt=t.getText(row,cols.patientname);				\r\n");
      out.write("				var v=null;\r\n");
      out.write("				if(t.getText(row,cols.patienttypecode)==\"1\"){\r\n");
      out.write("					v=l.callAjax(\"GET\",\"/waggle/service/ajax?id=inspatients&ic=0&corporate=\"+corporate+\"&searchtxt=\"+sTxt,\"\");\r\n");
      out.write("				}else{\r\n");
      out.write("					v=l.callAjax(\"GET\",\"/waggle/service/ajax?id=insoutpatients&ic=0&corporate=\"+corporate+\"&searchtxt=\"+sTxt,\"\");\r\n");
      out.write("				}\r\n");
      out.write("				if(v!=null && v.data.length==1){\r\n");
      out.write("					t.setText(row,cols.patientcode,v.data[0][0]);\r\n");
      out.write("					t.setText(row,cols.ipno,v.data[0][1]);\r\n");
      out.write("					t.setText(row,cols.patientname,v.data[0][2]);\r\n");
      out.write("					t.setCellTag(row,cols.patientname,v.data[0][2]);\r\n");
      out.write("					t.setText(row,cols.claimno,v.data[0][3]);\r\n");
      out.write("					t.setText(row,cols.billkey,v.data[0][4]);\r\n");
      out.write("					t.setText(row,cols.billno,v.data[0][5]);\r\n");
      out.write("					t.setText(row,cols.nursing,v.data[0][6]);\r\n");
      out.write("					t.setText(row,cols.invest,v.data[0][7]);\r\n");
      out.write("					t.setText(row,cols.pharmacy,v.data[0][8]);\r\n");
      out.write("					t.setText(row,cols.professional,v.data[0][9]);\r\n");
      out.write("					t.setText(row,cols.totalamount,v.data[0][10]);\r\n");
      out.write("				}else{\r\n");
      out.write("					t.setText(row,cols.patientname,\"\");				\r\n");
      out.write("					if(t.getText(row,cols.patienttypecode)==\"1\"){\r\n");
      out.write("						screenObjects.getScreenObject(\"claimgrid_data\").getColumnProperties()[cols.patientname].lovOptions.dsi=1;					\r\n");
      out.write("						screenObjects.getScreenObject(\"claimgrid_data\").getColumnProperties()[cols.patientname].lovOptions.ajax=\"inspatients\";\r\n");
      out.write("					}else{\r\n");
      out.write("						screenObjects.getScreenObject(\"claimgrid_data\").getColumnProperties()[cols.patientname].lovOptions.dsi=2;					\r\n");
      out.write("						screenObjects.getScreenObject(\"claimgrid_data\").getColumnProperties()[cols.patientname].lovOptions.ajax=\"insoutpatients\";\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			return true;\r\n");
      out.write("		}\r\n");
      out.write("	function addMasterData(){\r\n");
      out.write("		clearInnerScreen(); \r\n");
      out.write("  		$('#callback').css('display','block');\r\n");
      out.write("  		$('#xyz').css('display','none');\r\n");
      out.write("  		$('#datefilters').css('display','none');\r\n");
      out.write("  		$('#addGrp').css('display','none');\r\n");
      out.write("  		$('#btnSave').css(\"display\",\"inline-block\");\r\n");
      out.write("  	}\r\n");
      out.write("	function hideMasterData(){\r\n");
      out.write("  		clearInnerScreen();\r\n");
      out.write("  		$('#callback').css('display','none');\r\n");
      out.write("  		$('#xyz').css('display','block');\r\n");
      out.write("  		$('#datefilters').css('display','block');\r\n");
      out.write("  		$('#addGrp').css('display','block');\r\n");
      out.write("  		reloadGrid(500011);\r\n");
      out.write("  	}\r\n");
      out.write("	function toggleHeaderRow(){\r\n");
      out.write("  		toggleSearchToolBar(500011);\r\n");
      out.write("  	}\r\n");
      out.write("  	function loadOrderData(url,code,did){\r\n");
      out.write("	  	showLoader();\r\n");
      out.write("		var l=new FlexUI.Ajax();\r\n");
      out.write("		var v=l.callAjax(\"GET\",url,\"&screencode=21\");\r\n");
      out.write("		claims.loadObjectData(v);\r\n");
      out.write("		calculateTotal();\r\n");
      out.write("		$('#netAmt').html(screenObjects.getScreenObject(\"totalamt\").getValue());\r\n");
      out.write("		$('#callback').css('display','block');\r\n");
      out.write("	  	$('#xyz').css('display','none');\r\n");
      out.write("	  	$('#datefilters').css('display','none');\r\n");
      out.write("	  	$('#addGrp').css('display','none');\r\n");
      out.write("	  	$('#btnSave').css(\"display\",\"none\");  	\r\n");
      out.write("	  	hideLoader();\r\n");
      out.write("  	} \r\n");
      out.write("  	function reportGo(id){\r\n");
      out.write("		showLoader();\r\n");
      out.write("		var newParams=\"&fromdate=\"+$('#fromDate').val()+\"&todate=\"+$('#toDate').val();\r\n");
      out.write("		changeUrlAndReloadGrid(id,\"\",newParams);\r\n");
      out.write("		hideLoader();\r\n");
      out.write("	}\r\n");
      out.write("	toggleHeaderRow();\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
