/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.9
 * Generated at: 2024-07-19 08:16:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class expenseEntry_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("  <title>Receipts/Payments</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String code=(String)request.getParameter("code");
	String branch=(String)request.getParameter("branch");

      out.write("\r\n");
      out.write("<!-- JQ grid starts-->\r\n");
      out.write("<div id=\"xyz\" style='position:relative;border:0px;display:none;'></div>			    	 \r\n");
      out.write("<div id=\"callback\">\r\n");
      out.write("<div class=\"col-sm-12 col-md-12 col-lg-12 mpZero  mTBx1\" >\r\n");
      out.write("<div  class=\"panelOrange hcH\">\r\n");
      out.write("<div  class=\"subHe1\">\r\n");
      out.write("	Account Entry\r\n");
      out.write("   <div id=\"branch1\" class=\"brTp\" style=\"display:block\">\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"col-sm-12 col-md-12 col-lg-12 mpZero mTBx1\" id=\"divHide\">\r\n");
      out.write("	<div  id=\"divFirst\" class=\"mTBx1\">\r\n");
      out.write("\r\n");
      out.write("   <div class=\"col-sm-6 col-md-6 col-lg-6\">\r\n");
      out.write("    <div id=\"group1\" class=\"\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("   <div class=\"col-sm-6 col-md-6 col-lg-6\">                    \r\n");
      out.write("    <div id=\"trandetail\" class=\"\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("   <div class=\"clearfix\"></div>\r\n");
      out.write("	<div class=\"col-sm-6 col-md-6 col-lg-6\">                    \r\n");
      out.write("    <div id=\"paymentdetail\" class=\"\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("   <div class=\"col-sm-6 col-md-6 col-lg-6\">                    \r\n");
      out.write("    <div id=\"amountdetail\" class=\"\">\r\n");
      out.write("   </div></div>   \r\n");
      out.write("   <div class=\"clearfix\"></div>\r\n");
      out.write("   <div class=\"col-sm-12 col-md-12 col-lg-12\">\r\n");
      out.write("    <div id=\"chequedetails\" class=\"\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("   <div class=\"col-sm-12 col-md-12 col-lg-12\">\r\n");
      out.write("    <div id=\"carddetails\" class=\"\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div></div></div></div>\r\n");
      out.write("   <div class=\"clearfix\"></div>\r\n");
      out.write("   <div class=\"col-sm-12 col-md-12 col-lg-12 mpZero\">                    \r\n");
      out.write("    <div id=\"group2\" class=\"panelOrange hcH\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- JQ grid ends-->\r\n");
      out.write("<div style=\"position:fixed; bottom:0; width:94.5%; background:#fff; z-index:1000;\">\r\n");
      out.write("<div id=\"saveGrp\" class=\"\" >\r\n");
      out.write("	<button id=\"btnSave\" class=\"btn btn-primary priBut\" type=\"button\" onclick=\"save()\">Save</button>\r\n");
      out.write("    <button id=\"btnClear\" class=\"btn btn-default\" type=\"button\" onclick=\"add('')\">Cancel</button>\r\n");
      out.write("    <button id=\"btnEdit\" class=\"btn btn-default\" type=\"button\" onclick=\"edit('')\">Edit</button>	\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var l=new FlexUI.Ajax();\r\n");
      out.write("var v=l.callAjax(\"GET\",\"/waggle/service/ajax\",\"ic=0&id=userdefbranch\");\r\n");
      out.write("var defbranch=v.data;\r\n");
      out.write("\r\n");
      out.write("  var sProps={title:{height:25,width:100,name:\"Invoice\"},container:{id:\"callback\",isdialog:false},js:\"js/validations/expenseentry.js\",screen:[\r\n");
      out.write("  {name:\"branch1\",title:\"\",height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[{colno:0,name:\"branch\",inputType:0,type:\"LOV\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"refno\",lovOptions:{url:\"/waggle/service/ajax\",ajax:\"userbranch\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[]}}\r\n");
      out.write("  ]},\r\n");
      out.write("  {name:\"group1\",title:\"\",pcolumns:1,colcss:\"col-sm-12 col-md-12 col-lg-12\",height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[{colno:0,name:\"code\",inputType:0,type:\"INT\",caption:\"Code\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"branch\"},\r\n");
      out.write("  {colno:0,name:\"trantype\",inputType:1,type:\"TEXT\",caption:\"TranType\",mandatory:true,defaultValue:\"\",\"textLength\":10,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"account\",values:\"1~2~3\",keys:\"Receipt~Payment~Contra\",onchange:\"onVoucherTypeChange\"},\r\n");
      out.write("  {colno:0,name:\"account\",inputType:0,type:\"LOV\",caption:\"Name\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"trandate\",lovOptions:{url:\"/waggle/service/ajax\",ajax:\"ledgers\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"account\",tt:true,id:\"lm_code\"},{tgt:\"account\",tt:false,id:\"lm_name\"},{tgt:\"address\",tt:false,id:\"lm_address1,lm_address2,lm_city,lm_pincode\",m:true},{tgt:\"address1\",tt:false,id:\"lm_address1\"},{tgt:\"address2\",tt:false,id:\"lm_address2\"},{tgt:\"city\",tt:false,id:\"lm_city\"},{tgt:\"pincode\",tt:false,id:\"lm_pincode\"}]}},\r\n");
      out.write("  {colno:0,name:\"address1\",inputType:0,type:\"TEXT\",caption:\"Building\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"address3\"},\r\n");
      out.write("  {colno:0,name:\"address2\",inputType:0,type:\"TEXT\",caption:\"Street\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"city\"},\r\n");
      out.write("  {colno:0,name:\"city\",inputType:0,type:\"TEXT\",caption:\"City\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":50,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"pincode\"},\r\n");
      out.write("  {colno:0,name:\"pincode\",inputType:0,type:\"TEXT\",caption:\"PinCode\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"trandate\"},\r\n");
      out.write("  {colno:0,name:\"address\",inputType:4,type:\"SPAN\",caption:\"Address\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"address2\"}    \r\n");
      out.write("  ]},  \r\n");
      out.write("  {name:\"trandetail\",title:\"\",pcolumns:1,colcss:\"col-sm-12 col-md-12 col-lg-12\",height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"trandate\",inputType:0,type:\"DATE\",caption:\"Payment Date\",format:\"dd/mm/yy\",defaultValue:\"\",\"chkTag\":false,visible:true,readOnly:false,nf:\"refno\"},\r\n");
      out.write("  {colno:0,name:\"refno\",inputType:0,type:\"TEXT\",caption:\"Reference No\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"chkTag\":false,nf:\"total\"},\r\n");
      out.write("  {colno:0,name:\"acrefno\",inputType:0,type:\"INT\",caption:\"VNo\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"mode\"},\r\n");
      out.write("  {colno:0,name:\"acno\",inputType:0,type:\"INT\",caption:\"VNo\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"mode\"}  \r\n");
      out.write("  ]\r\n");
      out.write("  },\r\n");
      out.write("  {name:\"paymentdetail\",title:\"\",pcolumns:1,pcolumns:1,colcss:\"col-sm-12 col-md-12 col-lg-12\",height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"total\",inputType:0,type:\"DECIMAL\",caption:\"Amount:\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"discount\",onchange:\"onPaidChange\"},\r\n");
      out.write("  {colno:0,name:\"discount\",inputType:0,type:\"DECIMAL\",caption:\"Discount\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"charges\",onchange:\"onPaidChange\"},\r\n");
      out.write("  {colno:0,name:\"charges\",inputType:0,type:\"NEGDEC\",caption:\"Charges\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"totalamt\",onchange:\"onPaidChange\"}\r\n");
      out.write("  ]\r\n");
      out.write("  },\r\n");
      out.write("  {name:\"amountdetail\",title:\"\",pcolumns:1,colcss:\"col-sm-12 col-md-12 col-lg-12\",height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"totalamt\",inputType:0,type:\"DECIMAL\",caption:\"Net Amount\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"chkTag\":false,nf:\"mode\"},\r\n");
      out.write("  {colno:0,name:\"mode\",inputType:1,type:\"TEXT\",caption:\"Payment Mode\",keys:\"Cash~Cheque~Credit Card\",values:\"CA~CQ~CC\",defaultValue:\"CA\",\"readOnly\":false,\"chkTag\":false,nf:\"remarks\",visible:true,onchange:\"onModeChange\"}\r\n");
      out.write("  ]\r\n");
      out.write("  },\r\n");
      out.write("  {name:\"chequedetails\",title:\"\",pcolumns:2,height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"chequeno\",inputType:0,type:\"TEXT\",caption:\"Cheque No\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"chequedate\"},\r\n");
      out.write("  {colno:0,name:\"chequedate\",inputType:0,type:\"DATE\",caption:\"Cheque Date\",format:\"dd/mm/yy\",defaultValue:\"\",\"chkTag\":false,visible:true,nf:\"bankname\"},  \r\n");
      out.write("  {colno:1,name:\"bankname\",inputType:0,type:\"TEXT\",caption:\"Bank Name\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":50,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"bankbranch\"},\r\n");
      out.write("  {colno:1,name:\"bankbranch\",inputType:0,type:\"TEXT\",caption:\"Branch Name\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":50,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"outstanding_data\"}\r\n");
      out.write("  ]\r\n");
      out.write("  },\r\n");
      out.write("  {name:\"carddetails\",title:\"\",pcolumns:3,colcss:\"col-sm-4 col-md-4 col-lg-4\",height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"cardbank\",inputType:0,type:\"TEXT\",caption:\"Bank Name\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"cardtype\"},\r\n");
      out.write("  {colno:1,name:\"cardtype\",inputType:0,type:\"TEXT\",caption:\"Card Type\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"cardtranno\"},\r\n");
      out.write("  {colno:2,name:\"cardtranno\",inputType:0,type:\"TEXT\",caption:\"Transaction No\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"outstanding_data\"}\r\n");
      out.write("  ]\r\n");
      out.write("  },\r\n");
      out.write("  {name:\"bankdetails\",title:\"\",pcolumns:2,height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"bankledger\",inputType:0,type:\"LOV\",caption:\"Bank Ledger\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"remarks\",lovOptions:{url:\"/Fruits/service/ajax\",ajax:\"banks\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"bankledger\",tt:true,id:\"lm_code\"},{tgt:\"bankledger\",tt:false,id:\"lm_name\"}]}},\r\n");
      out.write("  ]\r\n");
      out.write("  },\r\n");
      out.write("  {name:\"group2\",title:\"\",height:15,width:45,minWidth:250,minHeight:50,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {name:\"remarks\",inputType:0,type:\"TEXTAREA\",caption:\"Note \",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":500,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"\"}\r\n");
      out.write("  ]\r\n");
      out.write("  }]};\r\n");
      out.write("  /*\r\n");
      out.write("  \r\n");
      out.write("  ,\r\n");
      out.write("    {name:\"group4\",height:15,width:80,minWidth:500,minHeight:50,colWidth:15,float:\"left\",backColor:\"beige\",contentType:\"Fields\",fields:[\r\n");
      out.write("    {name:\"add\",inputType:3,caption:\"Add\",onclick:\"add\",visible:true},\r\n");
      out.write("    {name:\"save\",inputType:3,caption:\"Save\",onclick:\"save\",visible:true},\r\n");
      out.write("    {name:\"edit\",inputType:3,caption:\"Edit\",onclick:\"edit\",visible:true},\r\n");
      out.write("    {name:\"Delete\",inputType:3,caption:\"Delete\",onclick:\"delete1\",visible:true}\r\n");
      out.write("    ]}\r\n");
      out.write("    */\r\n");
      out.write("  var payments=new FlexUI.Screen(\"payments\",sProps);\r\n");
      out.write("  setDefaultBranch();\r\n");
      out.write(" </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
