/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.9
 * Generated at: 2024-07-22 06:46:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class hospitalDashBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("    <head>\r\n");
      out.write("		<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("		<style>\r\n");
      out.write("					body{\r\n");
      out.write("			margin-top:20px;\r\n");
      out.write("			background:#FAFAFA;\r\n");
      out.write("			}\r\n");
      out.write("			.order-card {\r\n");
      out.write("				color: #fff;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			.bg-c-blue {\r\n");
      out.write("				background: linear-gradient(45deg,#4099ff,#73b4ff);\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			.bg-c-green {\r\n");
      out.write("				background: linear-gradient(45deg,#2ed8b6,#59e0c5);\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			.bg-c-yellow {\r\n");
      out.write("				background: linear-gradient(45deg,#FFB64D,#ffcb80);\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			.bg-c-pink {\r\n");
      out.write("				background: linear-gradient(45deg,#FF5370,#ff869a);\r\n");
      out.write("			}\r\n");
      out.write("			.bg-c-dark {\r\n");
      out.write("				background: linear-gradient(45deg,#3d3446,#ff869a);\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			.card {\r\n");
      out.write("				border-radius: 5px;\r\n");
      out.write("				-webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);\r\n");
      out.write("				box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);\r\n");
      out.write("				border: none;\r\n");
      out.write("				margin-bottom: 30px;\r\n");
      out.write("				-webkit-transition: all 0.3s ease-in-out;\r\n");
      out.write("				transition: all 0.3s ease-in-out;\r\n");
      out.write("			}\r\n");
      out.write("			.chart {\r\n");
      out.write("				border-radius: 0px;\r\n");
      out.write("				-webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);\r\n");
      out.write("				box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);\r\n");
      out.write("				border: black;\r\n");
      out.write("				margin-bottom: 30px;\r\n");
      out.write("				-webkit-transition: all 0.3s ease-in-out;\r\n");
      out.write("				transition: all 0.3s ease-in-out;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			.card .card-block {\r\n");
      out.write("				padding: 25px;\r\n");
      out.write("			}\r\n");
      out.write("			.card .card-block-bottom {\r\n");
      out.write("				padding: 15px;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.order-card i {\r\n");
      out.write("				font-size: 26px;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			.f-left {\r\n");
      out.write("				float: left;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			.f-right {\r\n");
      out.write("				float: right;\r\n");
      out.write("			}\r\n");
      out.write("			.header {\r\n");
      out.write("				overflow: hidden;\r\n");
      out.write("				background-color: #f1f1f1;\r\n");
      out.write("				padding: 10px 10px;\r\n");
      out.write("				}\r\n");
      out.write("		</style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    <script language=\"javascript\" type=\"text/javascript\" src=\"js/flot/jquery.flot.js\"></script>\r\n");
      out.write("	<script language=\"javascript\" type=\"text/javascript\" src=\"js/flot/jquery.flot.categories.js\"></script>\r\n");
      out.write("	<script language=\"javascript\" type=\"text/javascript\" src=\"js/flot/jquery.flot.tooltip.js\"></script>    \r\n");
      out.write("    <script>\r\n");
      out.write("    ");

    	String userId=(String)session.getAttribute("LOGIN_ID");
    	
      out.write("\r\n");
      out.write("    	function showDash(categoryid) {\r\n");
      out.write("    	var a=new FlexUI.Ajax();\r\n");
      out.write("		var v=a.callAjax(\"GET\",\"/waggle/service/account/dash\",\"&id=lastsevensales&term=&type=line\");\r\n");
      out.write("		\r\n");
      out.write("		var v1=a.callAjax(\"GET\",\"/waggle/service/account/dash\",\"&id=toptenproduct&term=\");\r\n");
      out.write("\r\n");
      out.write("		var data = v;\r\n");
      out.write("\r\n");
      out.write("		var series=[];\r\n");
      out.write("		var s=data.length;\r\n");
      out.write("		var maxAmount=0;\r\n");
      out.write("		var sdata=[];		\r\n");
      out.write("		for(var i=0;i<s;i++){\r\n");
      out.write("			var d;\r\n");
      out.write("			d=data[i];\r\n");
      out.write("			sdata.push([i,d[1]]);\r\n");
      out.write("			if(d[1]>maxAmount){\r\n");
      out.write("				maxAmount=d[1];\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		series.push({label:'Sales',data:sdata});\r\n");
      out.write("		\r\n");
      out.write("		$.plot(\"#flot-chart-bar\", series, {\r\n");
      out.write("		series: {\r\n");
      out.write("			lines: {\r\n");
      out.write("				show: true\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("		grid: {\r\n");
      out.write("				hoverable: true //IMPORTANT! this is needed for tooltip to work\r\n");
      out.write("			},\r\n");
      out.write("		yaxis: { min: 0 },\r\n");
      out.write("		xaxis: { tickFormatter: function (v, axis) {					\r\n");
      out.write("        			return data[v][0];\r\n");
      out.write("      			}\r\n");
      out.write("    	},\r\n");
      out.write("		tooltip: true,\r\n");
      out.write("		tooltipOpts: {\r\n");
      out.write("			content: \"'%s' is %y\",\r\n");
      out.write("			shifts: {\r\n");
      out.write("				x: -60,\r\n");
      out.write("				y: 25\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		});\r\n");
      out.write("		var tp=v1;\r\n");
      out.write("		$.plot(\"#toptenproduct\", [ tp ], {\r\n");
      out.write("			series: {\r\n");
      out.write("				bars: {\r\n");
      out.write("					show: true,\r\n");
      out.write("					barWidth: 0.6,\r\n");
      out.write("					align: \"center\"\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			xaxis: {\r\n");
      out.write("				mode: \"categories\",\r\n");
      out.write("				tickLength: 0\r\n");
      out.write("			},\r\n");
      out.write("			tooltip:true,\r\n");
      out.write("			grid: {\r\n");
      out.write("			hoverable: true \r\n");
      out.write("			},\r\n");
      out.write("			tooltipOpts: {\r\n");
      out.write("				content: \" %x = %y\",\r\n");
      out.write("				shifts: {\r\n");
      out.write("					x: -60,\r\n");
      out.write("					y: 25\r\n");
      out.write("				}\r\n");
      out.write("			}			\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("    	\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div id=\"divDash\" class=\"col-sm-12 col-md-12 col-lg-12 mTBx\" style=\"display:block\"> \r\n");
      out.write("	    <div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-4 col-xl-2\">\r\n");
      out.write("					<div class=\"card bg-c-blue order-card\">\r\n");
      out.write("						<div class=\"card-block\">\r\n");
      out.write("							<h6 class=\"m-b-20\">Today Admission</h6>\r\n");
      out.write("							<h2 class=\"text-right\"><i class=\"fa fa-calendar f-left\"></i><p id=\"todayadmission\" class=\"announcement-heading\"></p></h2>\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div  class=\"card-block-bottom\" style=\"border-radius: 10px;background: linear-gradient(45deg,#f3f3f3,#f3efef);\">\r\n");
      out.write("							<p class=\"m-b-0\" ></p>\r\n");
      out.write("							<a href=\"#\" onclick=\"dashClick('/report.do?id=710007&title=Sales&fromdash=true')\">Today Admission<span style=\"padding: 5px;\" class=\"mdi mdi-arrow-right\"></span></a>\r\n");
      out.write("						\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"col-md-4 col-xl-2\">\r\n");
      out.write("					<div class=\"card bg-c-green order-card\">\r\n");
      out.write("						<div class=\"card-block\">\r\n");
      out.write("							<h6 class=\"m-b-20\">Total Patients</h6>\r\n");
      out.write("							<h2 class=\"text-right\"><i class=\"fa fa-user-plus f-left\"></i><p id=\"totalpatients\" class=\"announcement-heading\"></p></h2>\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div  class=\"card-block-bottom\" style=\"border-radius: 10px;background: linear-gradient(45deg,#f3f3f3,#f3efef);\">\r\n");
      out.write("							<p class=\"m-b-0\" ></p>\r\n");
      out.write("							<a href=\"#\" onclick=\"dashClick('/report.do?id=710007&title=Sales&fromdash=true')\">Total Patients<span style=\"padding: 5px;\" class=\"mdi mdi-arrow-right\"></span></a>\r\n");
      out.write("						\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"col-md-4 col-xl-2\">\r\n");
      out.write("					<div class=\"card bg-c-yellow order-card\">\r\n");
      out.write("						<div class=\"card-block\">\r\n");
      out.write("							<h6 class=\"m-b-20\">SelfCare</h6>\r\n");
      out.write("							<h2 class=\"text-right\"><i class=\"fa fa-heartbeat f-left\"></i><p id=\"selcare\" class=\"announcement-heading\"></p></h2>\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div  class=\"card-block-bottom\" style=\"border-radius: 10px;background: linear-gradient(45deg,#f3f3f3,#f3efef);\">\r\n");
      out.write("							<p class=\"m-b-0\" ></p>\r\n");
      out.write("							<a href=\"#\" onclick=\"dashClick('/report.do?id=710006&title=NewOrders&fromdash=true')\"> SelfCare <span style=\"padding: 5px;\" class=\"mdi mdi-arrow-right\"></span></a>\r\n");
      out.write("						\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"col-md-4 col-xl-2\">\r\n");
      out.write("					<div class=\"card bg-c-pink order-card\">\r\n");
      out.write("						<div class=\"card-block\">\r\n");
      out.write("							<h6 class=\"m-b-20\">Corporates </h6>\r\n");
      out.write("							<h2 class=\"text-right\"><i class=\"fa fa-hospital-o f-left\"></i><p id=\"Sponsors\" class=\"announcement-heading\"></p></h2>\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div  class=\"card-block-bottom\" style=\"border-radius: 10px;background: linear-gradient(45deg,#f3f3f3,#f3efef);\">\r\n");
      out.write("							<p class=\"m-b-0\" ></p>\r\n");
      out.write("							<a href=\"#\" onclick=\"dashClick('/report.do?id=710013&title=PendingOrders&fromdash=true')\"> Corporates <span style=\"padding: 5px;\" class=\"mdi mdi-arrow-right\"></span></a>\r\n");
      out.write("						\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-4 col-xl-2\">\r\n");
      out.write("					<div class=\"card bg-c-dark order-card\">\r\n");
      out.write("						<div class=\"card-block\">\r\n");
      out.write("							<h6 class=\"m-b-20\">MLC </h6>\r\n");
      out.write("							<h2 class=\"text-right\"><i class=\"fa fa-list f-left\"></i><p id=\"mlc\" class=\"announcement-heading\"></p></h2>\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div  class=\"card-block-bottom\" style=\"border-radius: 10px;background: linear-gradient(45deg,#f3f3f3,#f3efef);\">\r\n");
      out.write("							<p class=\"m-b-0\" ></p>\r\n");
      out.write("							<a href=\"#\" onclick=\"dashClick('/report.do?id=710013&title=PendingOrders&fromdash=true')\"> MLC <span style=\"padding: 5px;\" class=\"mdi mdi-arrow-right\"></span></a>\r\n");
      out.write("						\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("    <!-- END DASHBOARD -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-6\">\r\n");
      out.write("            <div class=\"panel panel-info\">\r\n");
      out.write("              <div class=\"panel-heading\">\r\n");
      out.write("                <h3 class=\"panel-title\"><i class=\"fa fa-long-arrow-right\"></i>Doctor wise Patients</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"panel-body\">\r\n");
      out.write("                <div class=\"flot-chart\">\r\n");
      out.write("                  <div class=\"flot-chart-content\"  style=\"height:250px\"><table id=\"drwisepatients\" width=\"100%\" ></table></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"text-right\">\r\n");
      out.write("                  <a href=\"#\">View Details <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-6\">\r\n");
      out.write("            <div class=\"panel panel-info\">\r\n");
      out.write("              <div class=\"panel-heading\">\r\n");
      out.write("                <h3 class=\"panel-title\"><i class=\"fa fa-long-arrow-right\"></i> Room Status</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"panel-body\">\r\n");
      out.write("                <div class=\"flot-chart\">\r\n");
      out.write("                  <div class=\"flot-chart-content\"  style=\"height:250px;\"><table id=\"roomstatus\" width=\"100%\" ></table></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"text-right\">\r\n");
      out.write("                  <a href=\"#\">View Details <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-6\">\r\n");
      out.write("            <div class=\"panel panel-info\">\r\n");
      out.write("              <div class=\"panel-heading\">\r\n");
      out.write("                <h3 class=\"panel-title\"><i class=\"fa fa-long-arrow-right\"></i> Corporates</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"panel-body\">\r\n");
      out.write("                <div class=\"flot-chart\">\r\n");
      out.write("                  <div class=\"flot-chart-content\"  style=\"height:250px;\"><table id=\"sponsorstatus\" width=\"100%\" ></table></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"text-right\">\r\n");
      out.write("                  <a href=\"#\">View Details <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-6\">\r\n");
      out.write("            <div class=\"panel panel-info\">\r\n");
      out.write("              <div class=\"panel-heading\">\r\n");
      out.write("                <h3 class=\"panel-title\"><i class=\"fa fa-long-arrow-right\"></i> Labs</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"panel-body\">\r\n");
      out.write("                <div class=\"flot-chart\">\r\n");
      out.write("                  <div class=\"flot-chart-content\"  style=\"height:250px;\"><table id=\"labs\" width=\"100%\" ></table></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"text-right\">\r\n");
      out.write("                  <a href=\"#\">View Details <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"panel panel-info\">\r\n");
      out.write("              <div class=\"panel-heading\">\r\n");
      out.write("                <h3 class=\"panel-title\"><i class=\"fa fa-long-arrow-right\"></i> Lab Summary</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"panel-body\">\r\n");
      out.write("                <div class=\"flot-chart\">\r\n");
      out.write("                  <div class=\"flot-chart-content\"  style=\"height:250px;\"><table id=\"labbills\" width=\"100%\" ></table></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"text-right\">\r\n");
      out.write("                  <a href=\"#\">View Details <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"panel panel-info\">\r\n");
      out.write("              <div class=\"panel-heading\">\r\n");
      out.write("                <h3 class=\"panel-title\"><i class=\"fa fa-long-arrow-right\"></i> Discharge Summary</h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"panel-body\">\r\n");
      out.write("                <div class=\"flot-chart\">\r\n");
      out.write("                  <div class=\"flot-chart-content\"  style=\"height:250px;\"><table id=\"dischargesummary\" width=\"100%\" ></table></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"text-right\">\r\n");
      out.write("                  <a href=\"#\">View Details <i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"clear:both;\"></div>\r\n");
      out.write("    <div id=\"reportcontent\" style=\"display:none\">\r\n");
      out.write("        	\r\n");
      out.write("    </div>\r\n");
      out.write("	\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("initializeGrid(\"drwisepatients\",['Doctor Name','Patients #'],[\r\n");
      out.write("    {name:'doctorname',index:'doctorname', width:400, sortable:false,editable: false,edittype:\"text\"} ,    \r\n");
      out.write("	{name:'patients',index:'patients', width:100,editable: false,edittype:\"text\"}\r\n");
      out.write("     ],{doctorname:\"\",patients:\"\"},false,false);\r\n");
      out.write("     \r\n");
      out.write("   initializeGrid(\"roomstatus\",['Branch','Ward','Occupied #','Free #'],[\r\n");
      out.write("    {name:'branchname',index:'branchname', width:180, sortable:false,editable: false,edittype:\"text\"} ,\r\n");
      out.write("    {name:'ward',index:'ward', width:180, sortable:false,editable: false,edittype:\"text\"} ,    \r\n");
      out.write("	{name:'occupied',index:'occupied', width:100,editable: false,edittype:\"text\"},\r\n");
      out.write("	{name:'free',index:'free', width:70,editable: false,edittype:\"text\"}\r\n");
      out.write("     ],{ward:\"\",occupied:\"\",free:\"\"},false,false);\r\n");
      out.write("   \r\n");
      out.write("   initializeGrid(\"sponsorstatus\",['Corporate','Patients #'],[\r\n");
      out.write("    {name:'sponsors',index:'sponsors', width:400, sortable:false,editable: false,edittype:\"text\"} ,    \r\n");
      out.write("	{name:'patients',index:'patients', width:90,editable: false,edittype:\"text\"}\r\n");
      out.write("     ],{sponsors:\"\",patients:\"\"},false,false);\r\n");
      out.write("     \r\n");
      out.write("     initializeGrid(\"labs\",['Branch','In-Patients','Out-Patients'],[\r\n");
      out.write("    {name:'branch',index:'branch', width:200, sortable:false,editable: false,edittype:\"text\"} ,    \r\n");
      out.write("	{name:'ip',index:'ip', width:120,editable: false,edittype:\"text\"},\r\n");
      out.write("	{name:'op',index:'op', width:120,editable: false,edittype:\"text\"}\r\n");
      out.write("     ],{branch:\"\",category:\"\",ip:\"\",op:\"\"},false,false);\r\n");
      out.write("     \r\n");
      out.write("     initializeGrid(\"labbills\",['Branch','Cash','Credit','Card','Corporate','Total'],[\r\n");
      out.write("    {name:'branch',index:'branch', width:200, sortable:false,editable: false,edittype:\"text\"} ,    \r\n");
      out.write("	{name:'cash',index:'cash', width:120,editable: false,edittype:\"text\"},\r\n");
      out.write("	{name:'credit',index:'credit', width:120,editable: false,edittype:\"text\"},\r\n");
      out.write("	{name:'card',index:'card', width:120,editable: false,edittype:\"text\"},\r\n");
      out.write("	{name:'sponsor',index:'sponsor', width:120,editable: false,edittype:\"text\"},\r\n");
      out.write("	{name:'total',index:'total', width:120,editable: false,edittype:\"text\"}\r\n");
      out.write("     ],{branch:\"\",cash:\"\",credit:\"\",card:\"\",sponsor:\"\",total:\"\"},false,false);\r\n");
      out.write("     \r\n");
      out.write("     initializeGrid(\"dischargesummary\",['Branch','#Patients','Cash','Card','Corporate','Total'],[\r\n");
      out.write("    {name:'branch',index:'branch', width:200, sortable:false,editable: false,edittype:\"text\"} ,\r\n");
      out.write("    {name:'patients',index:'patients', width:120,editable: false,edittype:\"text\"},    \r\n");
      out.write("	{name:'cash',index:'cash', width:120,editable: false,edittype:\"text\"},\r\n");
      out.write("	{name:'card',index:'card', width:120,editable: false,edittype:\"text\"},\r\n");
      out.write("	{name:'sponsor',index:'sponsor', width:120,editable: false,edittype:\"text\"},\r\n");
      out.write("	{name:'total',index:'total', width:120,editable: false,edittype:\"text\"}\r\n");
      out.write("     ],{branch:\"\",patients:\"\",cash:\"\",card:\"\",sponsor:\"\",total:\"\"},false,false);\r\n");
      out.write("     \r\n");
      out.write("function loadOrderData(url,code){\r\n");
      out.write("		var a=new FlexUI.Ajax();\r\n");
      out.write("		var v=a.callAjax(\"GET\",url,code);\r\n");
      out.write("				\r\n");
      out.write("		\r\n");
      out.write("		$('#todayadmission').html(v['todayadmission']);\r\n");
      out.write("		$('#mlc').html(v['mlc']);\r\n");
      out.write("		$('#totalpatients').html(v['totalpatients']);\r\n");
      out.write("		$('#Sponsors').html(v['2']);\r\n");
      out.write("		$('#selcare').html(v['1']);\r\n");
      out.write("		\r\n");
      out.write("		for (var property in v) {\r\n");
      out.write("			if(property=='drwisepatients'){\r\n");
      out.write("	    		addGridRowWithData('drwisepatients',v[property]);\r\n");
      out.write("	    	}else if(property=='roomstatus'){\r\n");
      out.write("	    		addGridRowWithData('roomstatus',v[property]);\r\n");
      out.write("	    	}else if(property=='sponsorstatus'){\r\n");
      out.write("	    		addGridRowWithData('sponsorstatus',v[property]);\r\n");
      out.write("	    	}else if(property=='labs'){\r\n");
      out.write("	    		addGridRowWithData('labs',v[property]);\r\n");
      out.write("	    	}else if(property=='labstender'){\r\n");
      out.write("	    		addGridRowWithData('labbills',v[property]);\r\n");
      out.write("	    	}else if(property=='dischargedetails'){\r\n");
      out.write("	    		addGridRowWithData('dischargesummary',v[property]);\r\n");
      out.write("	    	}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("}\r\n");
      out.write("loadOrderData(\"/waggle/service/account/dashboard\",\"\");\r\n");
      out.write("\r\n");
      out.write("function dashClick(m){\r\n");
      out.write("	if(m!=null && m!=\"\" && m!=\"#\"){\r\n");
      out.write("		$(\"#divDash\").css(\"display\",\"none\");\r\n");
      out.write("		$(\"#reportcontent\").css(\"display\",\"block\");\r\n");
      out.write("		$(\"#reportcontent\").html(\"\");\r\n");
      out.write("		$(\"#reportcontent\").load(\"/HMS\"+m);\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</script>        \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
