/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.9
 * Generated at: 2024-07-19 08:16:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class journalEntry_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("  <title>Vouchers</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String code=(String)request.getParameter("code");
	String branch=(String)request.getParameter("branch");

      out.write("\r\n");
      out.write("<!-- JQ grid starts-->\r\n");
      out.write("<div id=\"xyz\" style='position:relative;border:0px;display:none;'></div>			    	 \r\n");
      out.write("<div id=\"callback\"  >\r\n");
      out.write("<div class=\"col-sm-12 col-md-12 col-lg-12 mpZero  mTBx1\" >\r\n");
      out.write("<div  class=\"panelOrange hcH\">\r\n");
      out.write("<div  class=\"subHe1\">\r\n");
      out.write("Vouchers\r\n");
      out.write("<span class=\"pull-right right-btn\" onclick=\"showHideField('ledgers')\"><b id=\"plusbutton1\" class=\"fa fa-angle-double-up\"></b></span></div>\r\n");
      out.write("   <div id=\"branch1\" class=\"brTp\" style=\"display:block\">\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"col-sm-12 col-md-12 col-lg-12 mpZero\" id=\"divHide\">\r\n");
      out.write("	<div  id=\"divFirst\">\r\n");
      out.write("	\r\n");
      out.write("   <div class=\"col-sm-7 col-md-7 col-lg-7\">\r\n");
      out.write("    <div id=\"group1\" class=\"\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("   <div class=\"col-sm-4 col-md-4 col-lg-4\">                    \r\n");
      out.write("    <div id=\"trandetail\" class=\"\">\r\n");
      out.write("   </div></div>   \r\n");
      out.write("   <div class=\"col-sm-1 col-md-1 col-lg-1\">\r\n");
      out.write("    <div id=\"dummyDiv\" class=\"\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("   <div class=\"clearfix\"></div>\r\n");
      out.write("   <div class=\"col-sm-12 col-md-12 col-lg-12 mpRes mTBx1\">\r\n");
      out.write("    <div id=\"ledgers\" class=\"panelOrange hcH\" style=\"height:300px;\">\r\n");
      out.write("   </div></div>   \r\n");
      out.write("   <div class=\"clearfix\"></div>\r\n");
      out.write("   <div class=\"col-sm-12 col-md-12 col-lg-12\" >\r\n");
      out.write("    <div id=\"chequedetails\" class=\"\" style=\"display:none\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("   <div class=\"col-sm-12 col-md-12 col-lg-12\">\r\n");
      out.write("    <div id=\"carddetails\" class=\"\" style=\"display:none\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div></div></div></div>\r\n");
      out.write("   <div class=\"clearfix\"></div>\r\n");
      out.write("   <div class=\"col-sm-12 col-md-12 col-lg-12 mpZero mTBx1\">                    \r\n");
      out.write("    <div id=\"group2\" class=\"panelOrange hcH\">\r\n");
      out.write("   </div></div>\r\n");
      out.write("   <div class=\"clearfix\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- JQ grid ends-->\r\n");
      out.write("<div style=\"position:fixed; bottom:0; width:94.5%; background:#fff; z-index:1000;\">\r\n");
      out.write("<div id=\"saveGrp\" class=\"\" >\r\n");
      out.write("	<button id=\"btnSave\" class=\"btn btn-primary priBut\" type=\"button\" onclick=\"save()\">Save</button>\r\n");
      out.write("    <button id=\"btnClear\" class=\"btn btn-default\" type=\"button\" onclick=\"add('')\">Cancel</button>\r\n");
      out.write("    <button id=\"btnEdit\" class=\"btn btn-primary priBut\" type=\"button\" onclick=\"edit('')\">Edit</button>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$('.butt_sav').click(function(e){\r\n");
      out.write("	e.preventDefault();\r\n");
      out.write("});\r\n");
      out.write("$('.butt_can').click(function(e){\r\n");
      out.write("	e.preventDefault();\r\n");
      out.write("});			 \r\n");
      out.write("var l=new FlexUI.Ajax();\r\n");
      out.write("var v=l.callAjax(\"GET\",\"/waggle/service/ajax\",\"ic=0&id=userdefbranch\");\r\n");
      out.write("var defbranch=v.data;\r\n");
      out.write("\r\n");
      out.write("  var sProps={title:{height:25,width:100,name:\"Invoice\"},container:{id:\"callback\",isdialog:false},js:\"js/validations/journalentry.js\",screen:[\r\n");
      out.write("  {name:\"branch1\",title:\"\",height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[{colno:0,name:\"branch\",inputType:0,type:\"LOV\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"refno\",lovOptions:{url:\"/waggle/service/ajax\",ajax:\"userbranch\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[]}}\r\n");
      out.write("  ]},\r\n");
      out.write("  {name:\"group1\",title:\"\",pcolumns:0,height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[{name:\"code\",inputType:0,type:\"INT\",caption:\"Code\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"branch\"},\r\n");
      out.write("  {name:\"trantype\",inputType:1,type:\"TEXT\",caption:\"TranType\",mandatory:true,defaultValue:\"\",\"textLength\":10,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"trandate\",values:\"2~1~3~4\",keys:\"Payment~Receipt~Contra~Journal\"}\r\n");
      out.write("  ]},\r\n");
      out.write("  {name:\"trandetail\",title:\"\",pcolumns:1,height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"trandate\",inputType:0,type:\"DATE\",caption:\"Date\",format:\"dd/mm/yy\",defaultValue:\"\",\"chkTag\":false,visible:true,nf:\"mode\"},\r\n");
      out.write("  {colno:0,name:\"refno\",inputType:0,type:\"TEXT\",caption:\"No\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"mode\"},\r\n");
      out.write("  {colno:0,name:\"mode\",inputType:1,type:\"TEXT\",caption:\"Mode\",keys:\"None~Cash~Cheque~Credit Card\",values:\"NA~CA~CQ~CC\",defaultValue:\"NA\",\"readOnly\":false,\"chkTag\":false,nf:\"ledgers_data\",visible:true,onchange:\"onModeChange\"}\r\n");
      out.write("  ]\r\n");
      out.write("  },\r\n");
      out.write("  {name:\"chequedetails\",title:\"\",pcolumns:2,height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"chequeno\",inputType:0,type:\"TEXT\",caption:\"Cheque No\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"chequedate\"},\r\n");
      out.write("  {colno:0,name:\"chequedate\",inputType:0,type:\"DATE\",caption:\"Cheque Date\",format:\"dd/mm/yy\",defaultValue:\"\",\"chkTag\":false,visible:true,nf:\"bankname\"},  \r\n");
      out.write("  {colno:1,name:\"bankname\",inputType:0,type:\"TEXT\",caption:\"Bank Name\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":50,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"bankbranch\"},\r\n");
      out.write("  {colno:1,name:\"bankbranch\",inputType:0,type:\"TEXT\",caption:\"Branch Name\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":50,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"outstanding_data\"}\r\n");
      out.write("  ]\r\n");
      out.write("  },\r\n");
      out.write("  {name:\"carddetails\",title:\"\",pcolumns:3,colcss:\"col-sm-4 col-md-4 col-lg-4\",height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"cardbank\",inputType:0,type:\"TEXT\",caption:\"Bank Name\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"cardtype\"},\r\n");
      out.write("  {colno:1,name:\"cardtype\",inputType:0,type:\"TEXT\",caption:\"Card Type\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"cardtranno\"},\r\n");
      out.write("  {colno:2,name:\"cardtranno\",inputType:0,type:\"TEXT\",caption:\"Transaction No\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"outstanding_data\"}\r\n");
      out.write("  ]\r\n");
      out.write("  },\r\n");
      out.write("  {name:\"ledgers\",title:\"\",height:30,width:98,minWidth:500,minHeight:250,colWidth:50,float:\"left\",backColor:\"biege\",contentType:\"Table\",tableProperties:{rowEmptyCheckColumn:\"account\",serialNumberColumn:\"sno\",rowObject:false,enableAddRow:true,enableDeleteRow:true,columns:[\r\n");
      out.write("    {order:\"0\",id: \"sno\", name: \"SNo\", field: \"sno\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":true,\"chkTag\":false,width:50,sno:true},\r\n");
      out.write("    {order:\"1\",id: \"crdr\", name: \"CrDr\", field: \"crdr\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":true,width:100,chkTag:false,onchange:\"crDrChange\",validation:\"validateCrdr\"},\r\n");
      out.write("    {order:\"2\",id: \"account\", name: \"Account\", field: \"account\",defaultValue:\"0\",\"inputType\":0,\"type\":\"LOV\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":true,width:200,chkTag:true,lovOptions:{url:\"/waggle/service/ajax\",ajax:\"ledgers\",scrollEnabled:true,searchFromList:false,dsi:0,eremove:false,params:[],results:[{tgt:\"ledgers_data\",row:\"cr\",col:\"account\",tt:true,id:\"lm_code\"},{tgt:\"ledgers_data\",row:\"cr\",col:\"account\",tt:false,id:\"lm_name\"},{tgt:\"ledgers_data\",row:\"cr\",col:\"billwise\",tt:false,id:\"lm_billwise\"},{tgt:\"ledgers_data\",row:\"cr\",col:\"groupcode\",tt:false,id:\"lm_groupcode\"}]}},\r\n");
      out.write("    {order:\"3\",id: \"dramount\", name: \"Debit\", field: \"dramount\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:100,chkTag:false,onchange:\"amountChange\",validation:\"validateCrdr\"},\r\n");
      out.write("    {order:\"4\",id: \"cramount\", name: \"Credit\", field: \"cramount\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:100,chkTag:false,onchange:\"amountChange\",validation:\"validateCrdr\"},\r\n");
      out.write("    {order:\"5\",id: \"billwise\", name: \"Billwise\", field: \"billwise\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"6\",id: \"groupcode\", name: \"Group\", field: \"groupcode\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false}\r\n");
      out.write("    ]}},\r\n");
      out.write("      {name:\"group2\",title:\"\",pcolumns:3,colcss:\"col-sm-4 col-md-4 col-lg-4\",height:15,width:45,minWidth:250,minHeight:50,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"creditamount\",inputType:0,type:\"DECIMAL\",caption:\"Total Debit\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"chkTag\":false},\r\n");
      out.write("  {colno:1,name:\"debitamount\",inputType:0,type:\"DECIMAL\",caption:\"Total Credit\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"chkTag\":false},\r\n");
      out.write("  {colno:2,name:\"remarks\",inputType:0,type:\"TEXTAREA\",caption:\"Note \",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":500,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"\"}\r\n");
      out.write("  ]\r\n");
      out.write("  }]};  \r\n");
      out.write("  var voucher=new FlexUI.Screen(\"vouchers\",sProps);\r\n");
      out.write("  setDefaultBranch();\r\n");
      out.write(" </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
