/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.9
 * Generated at: 2024-07-19 08:16:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("  <title>Registration</title>\r\n");
      out.write("  <style>\r\n");
      out.write("	.input-group-append {\r\n");
      out.write("		flex: 0 0 30%;\r\n");
      out.write("	}	\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");

String screencode=(String)request.getParameter("id");
String rptTitle=(String)request.getParameter("title");
String mode=request.getParameter("mode");
String code=request.getParameter("code");
String status=request.getParameter("status");
status="1";
String id=request.getParameter("id");
if(id==null){
	id="300006";
}

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"card border-0 shadow\">\r\n");
      out.write("		<div class=\"card-body lpage\" >\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row w-100\" >\r\n");
      out.write("				<div class=\"col-md-6 d-flex align-items-center\">\r\n");
      out.write("						<h4 class=\"header-title\">");
      out.print(rptTitle);
      out.write("  </h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div  class=\"col-md-6 text-right\" id=\"addGrp\"  style='display:block'>\r\n");
      out.write("					<div class=\"btn-group pull-right\" id=\"actionicons\">\r\n");
      out.write("						<button onclick=\"addMasterData()\" class=\"btn btn-edit\"><i class=\"mdi mdi-plus\"></i>Add</button>\r\n");
      out.write("						<button onclick=\"toggleHeaderRow()\" class=\"btn btn-clear mx-3\"><i class=\"mdi mdi-filter\"></i>Search</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div  class=\"col-md-6 text-right\" id=\"saveGrp\" style='display:none'>\r\n");
      out.write("					<div class=\"mb-3\" id=\"actButton\">\r\n");
      out.write("					        	<button id=\"btnSave\" class=\"btn btn-primary priBut\" type=\"button\" onclick=\"saveRegistration()\">Save</button>\r\n");
      out.write("				                <button id=\"btnClear\" class=\"btn btn-default\" type=\"button\" onclick=\"hideMasterData()\">Cancel</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\" id=\"jqcontainer\" style=\"display:block\"><div class=\"table-container\" ><div id=\"xyz\" class=\"w-100\"></div></div></div>	\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"callback\" style=\"display:none;font-size:13px\" >\r\n");
      out.write("				<div class=\"table-container\">\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"row\" >\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-md-6 col-sm-6 mpZero\">\r\n");
      out.write("							<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-3\" id=\"npatient\"><label>Patient Name <span>*</span></label></div>\r\n");
      out.write("								<div class=\"col-md-2\"><select class=\"form-control\" id=\"prefix\"></select></div>\r\n");
      out.write("								<div class=\"col-md-6\" id=\"npatientv\"><input type=\"text\" class=\"form-control\" id=\"patientname\"><input type=\"hidden\" class=\"form-control\" id=\"code\"><input type=\"hidden\" class=\"form-control\" id=\"patienttype\"><input type=\"hidden\" class=\"form-control\" id=\"branchcode\"><input type=\"hidden\" class=\"form-control\" id=\"refcode\"><input type=\"hidden\" class=\"form-control\" id=\"grouptype\"><input type=\"hidden\" class=\"form-control\" id=\"groupseqid\"><input type=\"hidden\" class=\"form-control\" id=\"dvmid\"><input type=\"hidden\" class=\"form-control\" id=\"tokenno\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"col-md-6 col-sm-6 mpZero\">\r\n");
      out.write("							<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-1\"><label></label></div>\r\n");
      out.write("								<div class=\"col-md-3\"><label>Age<span>*</span></label></div>\r\n");
      out.write("								<div class=\"col-md-6\"><input type=\"text\" class=\"form-control\" id=\"patientage\"></div>\r\n");
      out.write("								<div class=\"col-md-2\"><select class=\"form-control\" id=\"agetype\"></select></div>\r\n");
      out.write("							</div>	\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div  class=\"col-md-6 col-sm-6 mpZero\">		\r\n");
      out.write("							<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-3\"><label>Gender</label></div>\r\n");
      out.write("								<div class=\"col-md-8\"><select class=\"form-control\" id=\"gender\"></select></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div  class=\"col-md-6 col-sm-6 mpZero\">		\r\n");
      out.write("							<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-1\"><label></label></div>\r\n");
      out.write("								<div class=\"col-md-3\"><label>Consulting Doctor <span>*</span></label></div>\r\n");
      out.write("								<div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"consultingdr\"/><input type=\"hidden\" class=\"form-control\" id=\"doctorcode\"/></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"clearfix\"></div>\r\n");
      out.write("						<div class=\"col-md-6 col-sm-6 mpZero\" style=\"display:block\">\r\n");
      out.write("							<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-3\"><label>Referred By</label></div>\r\n");
      out.write("								<div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"referredby\"><input type=\"hidden\" class=\"form-control\" id=\"referralcode\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					  <div class=\"clearfix\"></div>\r\n");
      out.write("						<div class=\"col-md-12 col-sm-12 mpZero mt-2\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-6 col-sm-6 mpZero\">\r\n");
      out.write("									<div class=\"form-group mbotto\">\r\n");
      out.write("										<div class=\"col-md-3\"><label>Gaurdian</label></div>\r\n");
      out.write("										<div class=\"col-md-2\"><select class=\"form-control\" id=\"guardiantype\"></select></div>\r\n");
      out.write("										<div class=\"col-md-6\"><input type=\"text\" class=\"form-control\" id=\"guardianname\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>	\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"col-md-6 col-sm-6 mpZero\">\r\n");
      out.write("								<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-1\"><label></label></div>\r\n");
      out.write("								<div class=\"col-md-3\"><label>Address</label></div>\r\n");
      out.write("								<div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"address1\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								</div>	\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"col-md-6 col-sm-6 mpZero\"  style=\"display:none\">\r\n");
      out.write("								<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-3\"><label> </label></div>\r\n");
      out.write("								<div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"address2\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								</div>	\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"col-md-6 col-sm-6 mpZero\"  style=\"display:none\">\r\n");
      out.write("								<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-3\"><label></label></div>\r\n");
      out.write("								<div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"address3\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								</div>	\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"col-md-6 col-sm-6 mpZero\" >\r\n");
      out.write("								<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-3\"><label>Mobile No.</label></div>\r\n");
      out.write("								<div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"mobileno\" maxlength=\"10\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								</div>																	\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-md-12 col-sm-12 mpZero mt-3\" id=\"corporatedetails\" style=\"display:none\">\r\n");
      out.write("							<div class=\"subHe bline\"><h5>Corporate Details</h5></div>\r\n");
      out.write("							<div class=\"row mpZero\">\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("								<div class=\"col-md-6 col-sm-6 mpZero\">\r\n");
      out.write("								<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-3\"><label>Corporate</label></div>\r\n");
      out.write("								<div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"sponsorname\"><input type=\"hidden\" class=\"form-control\" id=\"sponsorcode\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6 col-sm-6 mpZero\">\r\n");
      out.write("								<div class=\"form-group mbotto\">\r\n");
      out.write("								<div class=\"col-md-1\"><label></label></div>\r\n");
      out.write("								<div class=\"col-md-3\"><label>Corporate Card No</label></div>\r\n");
      out.write("								<div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"sponsorcardno\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								</div>					\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"clearfix\"></div>\r\n");
      out.write("					\r\n");
      out.write("						<div class=\"col-md-12 col-sm-12 mpZero mt-3\" id=\"patientstatus\">\r\n");
      out.write("							<div class=\"subHe bline\"><h5>Initial Observation</h5></div>\r\n");
      out.write("							<div class=\"row mpZero\">\r\n");
      out.write("								<div class=\"col-md-6 col-sm-6 mpZero mb-3\">\r\n");
      out.write("									<div class=\"form-group mbotto\">\r\n");
      out.write("										<div class=\"col-md-3\"><label>Appointment  Date</label></div>\r\n");
      out.write("										<div class=\"col-md-2\"><input type=\"text\" class=\"form-control\" id=\"appdate\" ></div>\r\n");
      out.write("										<div class=\"col-md-6\">&nbsp;</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6 col-sm-6 mpZero mb-3\"></div>\r\n");
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"col-md-4 col-sm-4 mpZero\">\r\n");
      out.write("									<div class=\"form-group mbotto\">\r\n");
      out.write("										<div class=\"col-md-2\">\r\n");
      out.write("										  <label>Weight</label>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("										  <input type=\"text\" class=\"form-control\" id=\"weight\"  placeholder=\"Kgs\">\r\n");
      out.write("										 \r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-2 ms-2 \">\r\n");
      out.write("											<lebel>kgs</lebel>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-4 col-sm-4 mpZero\">\r\n");
      out.write("									<div class=\"form-group mbotto\">\r\n");
      out.write("										<div class=\"col-md-2\">\r\n");
      out.write("										<label>Height</label>\r\n");
      out.write("									  </div>\r\n");
      out.write("									  <div class=\"col-md-6\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"height\"  placeholder=\"cm\">\r\n");
      out.write("									  </div>\r\n");
      out.write("									  <div class=\"col-md-2 ms-2 \">\r\n");
      out.write("										  <lebel>cm</lebel>\r\n");
      out.write("									  </div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"col-md-4 col-sm-4 mpZero\">\r\n");
      out.write("									<div class=\"form-group mbotto\">\r\n");
      out.write("										<div class=\"col-md-2\">\r\n");
      out.write("										<label>PR</label>\r\n");
      out.write("									  </div>\r\n");
      out.write("									  <div class=\"col-md-6\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" id=\"pr\"  placeholder=\"/mt\">\r\n");
      out.write("									  </div>\r\n");
      out.write("									  <div class=\"col-md-2 ms-2 \">\r\n");
      out.write("										  <lebel>/mt</lebel>\r\n");
      out.write("									  </div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-4 col-sm-4 mpZero\">\r\n");
      out.write("									<div class=\"form-group mbotto\">\r\n");
      out.write("										<div class=\"col-md-2\">\r\n");
      out.write("										  <label>BP</label>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("										  <input type=\"text\" class=\"form-control\" id=\"bp\"  placeholder=\"mm/Hg\">\r\n");
      out.write("										  \r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-2 ms-2 \">\r\n");
      out.write("											<label>mm/Hg</label>\r\n");
      out.write("										  </div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-4 col-sm-4 mpZero\">\r\n");
      out.write("									<div class=\"form-group mbotto\">\r\n");
      out.write("										<div class=\"col-md-2\">\r\n");
      out.write("										  <label>BS</label>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("										  <input type=\"text\" class=\"form-control\" id=\"bs\"  placeholder=\"mgs/di\">\r\n");
      out.write("										  \r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-2 ms-2 \">\r\n");
      out.write("											<label>mgs/di</label>\r\n");
      out.write("										  </div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-4 col-sm-4 mpZero\">\r\n");
      out.write("									<div class=\"form-group mbotto\">\r\n");
      out.write("										<div class=\"col-md-2\">\r\n");
      out.write("										  <label>Temp</label>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-6\">\r\n");
      out.write("										  <input type=\"text\" class=\"form-control\" id=\"temp\"  placeholder=\"F\">\r\n");
      out.write("										 \r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-2 ms-2 \">\r\n");
      out.write("											<label>F</label>\r\n");
      out.write("										  </div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>						\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>   \r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    var ajaxObj=new FlexUI.Ajax();\r\n");
      out.write(" 	loadBranchData();\r\n");
      out.write(" 	");
if("300012".equals(id)){
      out.write("\r\n");
      out.write(" 		jqReport(300012,\"#xyz\",\"&branchcode=\"+$('#branch').val()+\"&status=");
      out.print(status);
      out.write("\");\r\n");
      out.write(" 		$('#corporatedetails').css(\"display\",\"none\");\r\n");
      out.write(" 	");
}else{
      out.write("\r\n");
      out.write(" 		jqReport(23,\"#xyz\",\"&branchcode=\"+$('#branch').val()+\"&status=");
      out.print(status);
      out.write("\");\r\n");
      out.write(" 	");
}
      out.write(" 	\r\n");
      out.write("    var sProps={js:\"\",screen:[\r\n");
      out.write("  	{name:\"group1\",predesigned:true,contentType:\"Fields\",\r\n");
      out.write("  	fields:[{name:\"code\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"branchcode\"},\r\n");
      out.write("  	{name:\"refcode\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"branchcode\"},\r\n");
      out.write("  	{name:\"branchcode\",inputType:0,type:\"INT\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"patienttype\"},\r\n");
      out.write("  	{name:\"patienttype\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"1\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"prefix\"},\r\n");
      out.write("  	{name:\"prefix\",inputType:1,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"patientname\",values:\"Mr~Mrs~Ms~Miss~Master\",keys:\"Mr~Mrs~Ms~Miss~Master\"},\r\n");
      out.write("  	{name:\"patientname\",inputType:0,type:\"TEXT\",caption:\"Patient Name\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"patientage\"},\r\n");
      out.write("  	{name:\"patientage\",inputType:0,type:\"INT\",caption:\"Age\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":3,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"agetype\"},\r\n");
      out.write("  	{name:\"agetype\",inputType:1,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"gender\",values:\"Yrs~Month\",keys:\"Yrs~Month\"},\r\n");
      out.write("  	{name:\"gender\",inputType:1,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"M\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"consultingdr\",values:\"M~F\",keys:\"Male~Female\"},\r\n");
      out.write("  	{name:\"consultingdr\",inputType:0,type:\"LOV\",caption:\"Consulting Doctor\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"guardiantype\",lovOptions:{url:\"/waggle/service/ajax\",ajax:\"consultdoctors\",scrollEnabled:true,searchFromList:false,cs:0,dsi:0,params:[],results:[{tgt:\"doctorcode\",tt:false,id:\"dr_code\"},{tgt:\"consultingdr\",tt:false,id:\"dr_name\"},{tgt:\"consultingdr\",tt:true,id:\"dr_name\"},{tgt:\"referralcode\",tt:false,id:\"dr_code\"},{tgt:\"referredby\",tt:false,id:\"dr_name\"},{tgt:\"referredby\",tt:true,id:\"dr_name\"}]}},\r\n");
      out.write("  	{name:\"doctorcode\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"referredby\"},\r\n");
      out.write("  	{name:\"referredby\",inputType:0,type:\"LOV\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"admissiondate\",lovOptions:{url:\"/waggle/service/ajax\",ajax:\"doctors\",scrollEnabled:true,searchFromList:false,cs:0,dsi:0,params:[],results:[{tgt:\"referralcode\",tt:false,id:\"dr_code\"},{tgt:\"referredby\",tt:false,id:\"dr_name\"},{tgt:\"referredby\",tt:true,id:\"dr_name\"}]}},\r\n");
      out.write("  	{name:\"referralcode\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"admissiontype\"},\r\n");
      out.write("	{name:\"guardiantype\",inputType:1,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"guardianname\",values:\"S/o~D/o~H/o~W/o~C/o~M/o~F/o\",keys:\"S/o~D/o~H/o~W/o~C/o~M/o~F/o\"},\r\n");
      out.write("	{name:\"guardianname\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":50,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"address1\"},  	\r\n");
      out.write("	{name:\"address1\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"mobileno\"},\r\n");
      out.write("	{name:\"address2\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"address3\"},\r\n");
      out.write("	{name:\"address3\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"mobileno\"},\r\n");
      out.write("	{name:\"mobileno\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"appdate\"},\r\n");
      out.write("	{name:\"appdate\",inputType:0,type:\"DATE\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"chkTag\":false,nf:\"height\"},\r\n");
      out.write("	{name:\"weight\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"weight\"},\r\n");
      out.write("	{name:\"height\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"pr\"},\r\n");
      out.write("	{name:\"pr\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"bp\"},\r\n");
      out.write("	{name:\"bp\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"bs\"},\r\n");
      out.write("	{name:\"bs\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"temp\"},\r\n");
      out.write("	{name:\"temp\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"btnSave\"},\r\n");
      out.write("	{name:\"sponsorcode\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"sponsorname\"},\r\n");
      out.write("  	{name:\"sponsorname\",inputType:0,type:\"LOV\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":true,nf:\"sponsorcardno\",lovOptions:{url:\"/waggle/service/ajax\",ajax:\"insurancecompany\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"sponsorname\",tt:false,id:\"icm_name\"},{tgt:\"sponsorname\",tt:true,id:\"icm_name\"},{tgt:\"sponsorcode\",tt:false,id:\"icm_code\"}]}},  	\r\n");
      out.write("  	{name:\"sponsorcardno\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"sponsorapprovalno\"},\r\n");
      out.write("  	{name:\"grouptype\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"\"},\r\n");
      out.write("  	{name:\"groupseqid\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"\"},\r\n");
      out.write("  	{name:\"dvmid\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"\"},\r\n");
      out.write("  	{name:\"tokenno\",inputType:0,type:\"INT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"\"},\r\n");
      out.write("	{name:\"btnSave\",inputType:3,caption:\"\",visible:false},\r\n");
      out.write("    {name:\"btnClear\",inputType:3,caption:\"\",visible:false}	  		\r\n");
      out.write("  	]}]};\r\n");
      out.write("	var registration=null;\r\n");
      out.write("	$('#screentitle').text(\"Admission\");\r\n");
      out.write("    function saveRegistration(){\r\n");
      out.write("    	if(registration.getSaveInProgress()) return;\r\n");
      out.write("    	var r=null;\r\n");
      out.write("    	var code=screenObjects.getScreenObject(\"code\").getValue();\r\n");
      out.write("    	if(code!=\"\" && code!=\"0\"){\r\n");
      out.write("	    	registration.setOperation(\"MOD\");\r\n");
      out.write("	    }else{\r\n");
      out.write("	    	registration.setOperation(\"ADD\");\r\n");
      out.write("	    }\r\n");
      out.write("    	registration.setScreenCode(23);\r\n");
      out.write("    	var d=registration.processDataToSave();\r\n");
      out.write("    	registration.setSaveInProgress(true);\r\n");
      out.write("		if(\"FAILED\"!=d){\r\n");
      out.write("			var s=new FlexUI.Ajax();\r\n");
      out.write("			showLoader();\r\n");
      out.write("			r=s.callAjax(\"POST\",\"/waggle/service/screen/save\",d);\r\n");
      out.write("			hideLoader();\r\n");
      out.write("		 }else{\r\n");
      out.write("		 	registration.setSaveInProgress(false);\r\n");
      out.write("		 	alert(\"Please correct the validation errors and continue...\");\r\n");
      out.write("		 	return;\r\n");
      out.write("		 }	\r\n");
      out.write("		 if(r.result==\"Success\"){\r\n");
      out.write("		 	");
if("300012".equals(id)){
      out.write("\r\n");
      out.write("				if(code!=0){\r\n");
      out.write("				setErrorMessage(r.message+\" [No:\"+ groupseqid.value+\"]\")   ;\r\n");
      out.write("			}else{\r\n");
      out.write("				setErrorMessage(r.message+\" [No:\"+r.groupseqid+\"]\")   ;\r\n");
      out.write("			}\r\n");
      out.write("			");
}else{
      out.write("\r\n");
      out.write("				if(code!=0){\r\n");
      out.write("				setErrorMessage(r.message+\" [No:\"+code+\"]\")   ;\r\n");
      out.write("				}else{\r\n");
      out.write("				setErrorMessage(r.message+\" [No:\"+r.code+\"]\") ;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				if(window.confirm(\"Do you want to print the bill?\")){\r\n");
      out.write("					printPrescription(r.code);\r\n");
      out.write("				}\r\n");
      out.write("			");
}
      out.write("\r\n");
      out.write("			var ps=JSON.parse(d.replace(\"data=\",\"\")).savedata;\r\n");
      out.write("			clearInnerScreen();\r\n");
      out.write("			hideMasterData();\r\n");
      out.write("			return r.key;			\r\n");
      out.write("		}else{\r\n");
      out.write("			registration.setSaveInProgress(false);\r\n");
      out.write("			alert(r.message);		\r\n");
      out.write("		}\r\n");
      out.write("    }\r\n");
      out.write("    function loadOrderData(url,code,did){\r\n");
      out.write("    	var rowData=undefined;\r\n");
      out.write("		 ");
if("300012".equals(id)){
      out.write("\r\n");
      out.write("    		rowData=$(\"#report_300012\").getRowData(did);\r\n");
      out.write("		");
}else{
      out.write("\r\n");
      out.write("	    	rowData=$(\"#report_23\").getRowData(did);\r\n");
      out.write("		");
}
      out.write("\r\n");
      out.write("  		showLoader();\r\n");
      out.write("		var l=new FlexUI.Ajax();\r\n");
      out.write("		var v=l.callAjax(\"GET\",\"/waggle/service/screen/data?screencode=23\",\"&branchcode=\"+$('#branch').val()+\"&patientcode=\"+rowData.prm_code);\r\n");
      out.write("		registration.loadObjectData(v);\r\n");
      out.write("		$('#callback').css('display','block');\r\n");
      out.write("		$('#xyz').css('display','none');\r\n");
      out.write("  		$('#jqcontainer').css('display','none');\r\n");
      out.write("  		$('#addGrp').css('display','none');\r\n");
      out.write("		$('#saveGrp').css('display','block');\r\n");
      out.write("  		hideLoader();\r\n");
      out.write("  		screenObjects.getScreenObject(\"patientname\").focus();\r\n");
      out.write("  		$('#btnSave').css('display','inline-block');\r\n");
      out.write("    }\r\n");
      out.write("    function clearInnerScreen(){\r\n");
      out.write("    	registration.clearScreen();\r\n");
      out.write("    	registration.setSaveInProgress(false);\r\n");
      out.write("    	$(\"patientname\").focus();\r\n");
      out.write("    	screenObjects.getScreenObject(\"branchcode\").setValue($('#branch').val());\r\n");
      out.write("    	");
if("300012".equals(id)){
      out.write("\r\n");
      out.write("			screenObjects.getScreenObject(\"grouptype\").setValue(\"1\");\r\n");
      out.write("		");
}
      out.write("\r\n");
      out.write("	screenObjects.getScreenObject(\"address1\").setValue(\"ARUPPUKOTTAI\");\r\n");
      out.write("    	screenObjects.getScreenObject(\"patientname\").focus();\r\n");
      out.write("    }\r\n");
      out.write("  function addMasterData(){ \r\n");
      out.write("  	clearInnerScreen();\r\n");
      out.write("  	$('#callback').css('display','block');\r\n");
      out.write("  	$('#xyz').css('display','none');\r\n");
      out.write("	$('#jqcontainer').css('display','none');\r\n");
      out.write("  	$('#addGrp').css('display','none');\r\n");
      out.write("	$('#saveGrp').css('display','block');\r\n");
      out.write("  }\r\n");
      out.write("  function hideMasterData(){\r\n");
      out.write("  	clearInnerScreen();\r\n");
      out.write("  	$('#callback').css('display','none');\r\n");
      out.write("  	$('#xyz').css('display','block');\r\n");
      out.write("	$('#jqcontainer').css('display','block');\r\n");
      out.write("  	$('#addGrp').css('display','block');\r\n");
      out.write("	$('#saveGrp').css('display','none');\r\n");
      out.write("  	");
if("300012".equals(id)){
      out.write("\r\n");
      out.write("  		reloadGrid(300012);\r\n");
      out.write("  	");
}else{
      out.write("\r\n");
      out.write("  		reloadGrid(23);\r\n");
      out.write("  	");
}
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("  function toggleHeaderRow(){\r\n");
      out.write("  	");
if("300012".equals(id)){
      out.write("\r\n");
      out.write("  		toggleSearchToolBar(300012);\r\n");
      out.write("  	");
}else{
      out.write("\r\n");
      out.write("  		toggleSearchToolBar(23);\r\n");
      out.write("  	");
}
      out.write("  	\r\n");
      out.write("  }\r\n");
      out.write("  toggleHeaderRow();\r\n");
      out.write("  $(document).ready(function () {\r\n");
      out.write("		registration=new FlexUI.Screen(\"registration\",sProps);\r\n");
      out.write("		screenObjects.getScreenObject(\"branchcode\").setValue(1);\r\n");
      out.write("		");
if("300012".equals(id)){
      out.write("\r\n");
      out.write("			screenObjects.getScreenObject(\"grouptype\").setValue(\"1\");\r\n");
      out.write("		");
}
      out.write("\r\n");
      out.write("		screenObjects.getScreenObject(\"patientname\").focus();\r\n");
      out.write("   });\r\n");
      out.write("   function printPrescription(code){\r\n");
      out.write("   		var ccode=screenObjects.getScreenObject(\"code\").getValue();\r\n");
      out.write("   		if(ccode==\"\" || ccode==\"0\") ccode=code;\r\n");
      out.write("   		var l=new FlexUI.Ajax();\r\n");
      out.write("   		var v=l.callAjax(\"GET\",\"/waggle/service/screen/data?screencode=23\",\"&branchcode=\"+$('#branch').val()+\"&patientcode=\"+ccode);\r\n");
      out.write("   		v[\"type\"]=\"RECP\";\r\n");
      out.write("   		$.ajax({\r\n");
      out.write("            url: \"http://localhost:9191\",\r\n");
      out.write("            type: \"POST\",\r\n");
      out.write("            async: true,\r\n");
      out.write("            contentType:\"application/x-www-form-urlencoded\",\r\n");
      out.write("            data:\"printdata=\"+JSON.stringify(v),\r\n");
      out.write("            dataType: \"json\",\r\n");
      out.write("            success: function (r) {\r\n");
      out.write("				//alert(r.result);		\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("   }\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
