/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.9
 * Generated at: 2024-07-19 08:16:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class SessionClosing_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("  <title>Admission</title>\r\n");
      out.write("</head>\r\n");
String mode=request.getParameter("mode");
String code=request.getParameter("code");

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"clearfix\"></div>\r\n");
      out.write("	<div class=\"col-md-12 col-sm-12 mpZero marTp\">\r\n");
      out.write("			<div class=\"col-md-12 panelOrange hcH\" >\r\n");
      out.write("					<div class=\"subHe\">Session Details</div>\r\n");
      out.write("					<div class=\"col-md-12 col-sm-12 mpZero\" style=\"display:none\">\r\n");
      out.write("						<div class=\"form-group mbotto\">\r\n");
      out.write("						<div class=\"col-md-2\"><label>Type</label></div>\r\n");
      out.write("						<div class=\"col-md-10\"><select id=\"stype\"></select></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("					<div class=\"col-md-6 col-sm-6 mpZero\">\r\n");
      out.write("						<div class=\"form-group mbotto\">\r\n");
      out.write("						<div class=\"col-md-2\"><label>Branch</label></div>\r\n");
      out.write("						<div class=\"col-md-10\"><select class=\"form-control\" id='branch' onchange=\"changeBranchCodeAndClearSubScreenData()\"></select></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6 col-sm-6 mpZero\">\r\n");
      out.write("						<div class=\"form-group mbotto\">\r\n");
      out.write("						<div class=\"col-md-2\"><label>Taken Time</label></div>\r\n");
      out.write("						<div class=\"col-md-10\"><input type=\"text\" class=\"form-control\" id=\"processdate\" disabled/></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"clearfix\"></div>					\r\n");
      out.write("					<div class=\"col-md-12 col-sm-12 mpZero\" style=\"display:none\">\r\n");
      out.write("						<div class=\"form-group mbotto\">\r\n");
      out.write("						<div class=\"col-md-2\"><label>User</label></div>\r\n");
      out.write("						<div class=\"col-md-10\"><input type=\"text\" id=\"username\"/><input type=\"hidden\" id=\"userid\"/></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"clearfix\"></div>					\r\n");
      out.write("					<div class=\"col-md-12 col-sm-12 mpZero\">\r\n");
      out.write("						<div  class=\"col-md-6 col-sm-6 mpZero\">		\r\n");
      out.write("						<div class=\"form-group mbotto\">\r\n");
      out.write("							<div class=\"col-md-2\"><label>Date</label></div>\r\n");
      out.write("							<div class=\"col-md-10\"><input type=\"text\" class=\"form-control\" id=\"starttime\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						</div>	\r\n");
      out.write("						<div  class=\"col-md-6 col-sm-6 mpZero\" style=\"display:none\">		\r\n");
      out.write("						<div class=\"form-group mbotto\">\r\n");
      out.write("							<div class=\"col-md-4\"><label>End Time</label></div>\r\n");
      out.write("							<div class=\"col-md-8\"><input type=\"text\" class=\"form-control\" id=\"endtime\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>					\r\n");
      out.write("					<div class=\"clearfix\"></div>	\r\n");
      out.write("	            	<div id=\"actButton\" class=\"col-md-12 text-right\">\r\n");
      out.write("	                	<button id=\"btnGenerate\" class=\"btn btn-primary priBut\" type=\"button\" onclick=\"printSession(false)\">Generate</button>\r\n");
      out.write("	                	<button id=\"btnPrint\" class=\"btn btn-primary priBut\" type=\"button\" onclick=\"printSession(true)\">Print</button>\r\n");
      out.write("		                <button id=\"btnClear\" class=\"btn btn-default\" type=\"button\" onclick=\"clearInnerScreen()\">Clear</button>\r\n");
      out.write("	            	</div>\r\n");
      out.write("	            	<div class=\"clearfix\"></div>\r\n");
      out.write("					<div id=\"clbal\" style='position:relative;border:0px;display:block;' class=\"mTBx\">\r\n");
      out.write("        				<div style=\"background:#fedc34; display:inline-block; width:100%; padding:5px 10px;text-align:right\" >\r\n");
      out.write("				    	<div class=\"netAm\" id=\"netCash\">Net Cash 0.00</div>\r\n");
      out.write("    				</div>\r\n");
      out.write("        			</div>\r\n");
      out.write("	            	<div class=\"clearfix\"></div>\r\n");
      out.write("	            	<div class=\"col-md-12 col-sm-12 mpZero\">\r\n");
      out.write("	            		<div class=\"col-md-12 col-sm-12 mpZero\" id=\"bills\" style=\"height:360px;display:block\">\r\n");
      out.write("							<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"cashdetails\"></table>\r\n");
      out.write("		  				</div>\r\n");
      out.write("	            	</div>\r\n");
      out.write("			</div>		\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write(" 	loadBranchData();\r\n");
      out.write(" 	var sProps={js:\"\",screen:[\r\n");
      out.write("  	{name:\"group1\",predesigned:true,contentType:\"Fields\",\r\n");
      out.write("  	fields:[{name:\"branchcode\",inputType:0,type:\"INT\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"stype\"},\r\n");
      out.write("  	{name:\"stype\",inputType:1,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"M\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"username\",values:\"1~2\",keys:\"IP~OP\"},\r\n");
      out.write("  	{name:\"username\",inputType:0,type:\"LOV\",caption:\"\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"starttime\",lovOptions:{url:\"/waggle/service/ajax\",ajax:\"branchemployee\",scrollEnabled:true,searchFromList:false,dsi:0,params:[{n:\"branch\",src:\"branchcode\",ft:false}],results:[{tgt:\"username\",tt:false,id:\"em_name\"},{tgt:\"userid\",tt:false,id:\"em_code\"}]}},\r\n");
      out.write("  	{name:\"userid\",inputType:0,type:\"INT\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"starttime\"},\r\n");
      out.write("  	{name:\"starttime\",inputType:0,type:\"DATE\",caption:\"Date\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"btnGenerate\"},\r\n");
      out.write("  	{name:\"endtime\",inputType:0,type:\"DATETIME\",caption:\"End Time\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"\"},\r\n");
      out.write("  	{name:\"processdate\",inputType:0,type:\"TEXT\",caption:\"Taken Time\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"chkTag\":false,nf:\"\"},\r\n");
      out.write("	{name:\"btnGenerate\",inputType:3,caption:\"\",visible:false},\r\n");
      out.write("    {name:\"btnClear\",inputType:3,caption:\"\",visible:false}	  		\r\n");
      out.write("  	]}]};\r\n");
      out.write("	var sessionClose=null;	\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("    		sessionClose=new FlexUI.Screen(\"sessionclose\",sProps);\r\n");
      out.write("            $('#subtitle').text(\"\");\r\n");
      out.write("            $('#screentitle').text(\"Session Closing\");\r\n");
      out.write("            screenObjects.getScreenObject(\"starttime\").setValue(formatDateddMMyyyy(new Date()));\r\n");
      out.write("            screenObjects.getScreenObject(\"branchcode\").setValue($('#branch').val());\r\n");
      out.write("            ConstructCashGrid();            \r\n");
      out.write("     });\r\n");
      out.write("    function clearInnerScreen(){\r\n");
      out.write("    	sessionClose.clearScreen();\r\n");
      out.write("    	$(\"stype\").focus();\r\n");
      out.write("    	screenObjects.getScreenObject(\"branchcode\").setValue($('#branch').val());\r\n");
      out.write("    	clearGrid();\r\n");
      out.write("    }\r\n");
      out.write("	function printSession(print){\r\n");
      out.write("	    var data;\r\n");
      out.write("	    var startTime=screenObjects.getScreenObject(\"starttime\").getValue();\r\n");
      out.write("	    var endTime=screenObjects.getScreenObject(\"endtime\").getValue();\r\n");
      out.write("	    var type=screenObjects.getScreenObject(\"stype\").getValue();\r\n");
      out.write("	    var branch=screenObjects.getScreenObject(\"branchcode\").getValue();\r\n");
      out.write("	    //var userId=screenObjects.getScreenObject(\"userid\").getValue();\r\n");
      out.write("		$.ajax({\r\n");
      out.write("            url: \"/waggle/service/session?userid=0&type=1&branchcode=\"+branch+\"&starttime=\"+startTime+\"&displaydp=0\",\r\n");
      out.write("            type: \"GET\",\r\n");
      out.write("            async: false,\r\n");
      out.write("            contentType:\"application/json\",\r\n");
      out.write("            dataType: \"json\",\r\n");
      out.write("            success: function (r) {\r\n");
      out.write("				data=r;		\r\n");
      out.write("            }\r\n");
      out.write("        });			\r\n");
      out.write("        if(print){\r\n");
      out.write("        	data[\"displaydp\"]=\"0\";\r\n");
      out.write("			if(data.status==\"Success\"){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("		            url: \"http://localhost:9191\",\r\n");
      out.write("		            type: \"POST\",\r\n");
      out.write("		            async: true,\r\n");
      out.write("		            contentType:\"application/x-www-form-urlencoded\",\r\n");
      out.write("		            data:\"printdata=\"+JSON.stringify(data),\r\n");
      out.write("		            dataType: \"json\",\r\n");
      out.write("		            success: function (r) {\r\n");
      out.write("						//alert(r.result);		\r\n");
      out.write("		            }\r\n");
      out.write("		        });\r\n");
      out.write("		     }else{\r\n");
      out.write("		     	alert(data.message);\r\n");
      out.write("		     }			\r\n");
      out.write("	    }else{\r\n");
      out.write("	    	clearGrid();\r\n");
      out.write("	        $grid = $(\"#cashdetails\");\r\n");
      out.write("	        $grid.clearGridData();\r\n");
      out.write("	        $grid.jqGrid('setGridParam', { data: data[\"cashdetails\"] });\r\n");
      out.write("	        $grid[0].refreshIndex();\r\n");
      out.write("	        $grid.trigger(\"reloadGrid\");\r\n");
      out.write("	        $grid.footerData('set',{\"cash\":data[\"totalcash\"],\"card\":data[\"totalcard\"],\"sponsor\":data[\"totalsponsor\"],\"credit\":data[\"totalcredit\"]},false);\r\n");
      out.write("	        $('#netCash').text(\"Net Cash : \"+data[\"totalcash\"]);        	\r\n");
      out.write("	        screenObjects.getScreenObject(\"processdate\").setValue(data[\"gendate\"]);		\r\n");
      out.write("	    }			\r\n");
      out.write("	}\r\n");
      out.write("	function ConstructCashGrid() {\r\n");
      out.write("        var areaWidth = 800;\r\n");
      out.write("        $(\"#cashdetails\").jqGrid({\r\n");
      out.write("            datatype: \"local\",\r\n");
      out.write("            //width: areaWidth,\r\n");
      out.write("            height:350,\r\n");
      out.write("            autowidth: true,\r\n");
      out.write("            shrinktofit:true,\r\n");
      out.write("            colNames: ['BU', 'Cash', 'Card','Sponsor','Credit'],\r\n");
      out.write("            colModel: [\r\n");
      out.write("                        { name: 'buname', index: 'billno', sorttype: \"integer\", sortable: false, width: 250, align: 'left'},\r\n");
      out.write("                        { name: 'cash', index: 'cash', sorttype: \"text\", sortable: false, width: 100, align: 'right' },\r\n");
      out.write("						{ name: 'card', index: 'card', sorttype: \"text\", sortable: false, width: 200, align: 'right' },\r\n");
      out.write("						{ name: 'sponsor', index: 'sponsor', sorttype: \"text\", sortable: false, width: 200, align: 'right' },\r\n");
      out.write("						{ name: 'credit', index: 'credit', sorttype: \"text\", sortable: false, width: 0, align: 'left' }\r\n");
      out.write("            ],\r\n");
      out.write("            rowNum: 500,\r\n");
      out.write("            footerrow:true,\r\n");
      out.write("            userDataOnFooter:true,            \r\n");
      out.write("            datatype: \"jsonstring\",\r\n");
      out.write("            jsonReader: { repeatitems: false },\r\n");
      out.write("            viewrecords: true,\r\n");
      out.write("            gridview: true,\r\n");
      out.write("            loadtext: \"Loading....\",\r\n");
      out.write("            multiselect: false,\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    function clearGrid(){    	\r\n");
      out.write("    	$grid = $(\"#cashdetails\");\r\n");
      out.write("    	$grid.clearGridData();\r\n");
      out.write("    	$grid.jqGrid('setGridParam', { data: [] });\r\n");
      out.write("    	$grid[0].refreshIndex();\r\n");
      out.write("    	$grid.trigger(\"reloadGrid\");\r\n");
      out.write("    	$('#netCash').text(\"Net Cash : 0.00\");\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
