/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.9
 * Generated at: 2024-03-04 12:08:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<title>CISSOL Technologies</title>\r\n");
      out.write("	<meta charset=\"utf-8\" name=\"viewport\" content= \"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<link rel=\"shortcut icon\" href=\"images/titleicon.gif\">\r\n");
      out.write("  	<link rel=\"icon\" href=\"images/titleicon.gif\">\r\n");
      out.write("   \r\n");
      out.write("     <!-- plugins:css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("    <!-- endinject -->\r\n");
      out.write("    <!-- Plugin css for this page -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/jvectormap/jquery-jvectormap.css\">\r\n");
      out.write("    <!-- End plugin css for this page -->\r\n");
      out.write("    <!-- Bootstrap css for this page -->\r\n");
      out.write("	\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/demo/bootstrap.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/demo/bootstrap-datepicker.css\">\r\n");
      out.write("	<!-- <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'> --> \r\n");
      out.write("	\r\n");
      out.write("    <!-- End Bootstrap css for this page -->\r\n");
      out.write("    <!-- Layout styles -->\r\n");
      out.write("	\r\n");
      out.write("	 \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/demo/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/demo/custom_style.css\">\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/demo/ui.jqgrid-bootstrap.css\" type=\"text/css\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/demo/searchFilter.min.css\" type=\"text/css\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/demo/xgrid.css\" type=\"text/css\"/>\r\n");
      out.write("	\r\n");
      out.write("	<!-- LATO FONT -->\r\n");
      out.write("\r\n");
      out.write("	<link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>\r\n");
      out.write("    <!-- End layout styles -->\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]\r\n");
      out.write("	 -->\r\n");
      out.write("	\r\n");
      out.write("	 <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- plugins:js -->\r\n");
      out.write("    <!-- endinject -->\r\n");
      out.write("    \r\n");
      out.write("	  <!-- Bootstrap js for this page-->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"assets/vendors/js/vendor.bundle.base.js\"></script>  \r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/autocomplete.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    <!-- End Bootstrap js for this page-->\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<!-- Component js for this page-->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/jqgrid/i18n/grid.locale-en.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/jqgrid/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/core.js\"></script>	 \r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/newtext.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/table.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/lov.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/xgrid.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/newscreen.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/jqimpl.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/actions.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/dateextn.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<script src=\"assets/js/dashboard.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/key-bindings.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body >\r\n");
      out.write("	<script src=\"assets/js/preloader.js\"></script>\r\n");
      out.write("	");

		String userId=(String)session.getAttribute("LOGIN_ID");
		String src=(String)request.getParameter("src");
		if(src==null){
			src="";
		}
		String menuID=(String)request.getParameter("menuID");
		String subMenuID=(String)request.getParameter("subMenuID");
		String parameters=(String)request.getParameter("parameters");
		if(parameters==null){
			parameters="";
		}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<div class=\"body-wrapper\">\r\n");
      out.write("<div class=\"loader1\" id=\"divLoading\" style=\"display:none\">\r\n");
      out.write("    <div class=\"circles\">\r\n");
      out.write("    		Loading...\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<header class=\"mdc-top-app-bar\">\r\n");
      out.write("            <div class=\"mdc-top-app-bar__row\">\r\n");
      out.write("                <div class=\"col-sm-11\">\r\n");
      out.write("                    <div class=\"mdc-top-app-bar__section mdc-top-app-bar__section--align-start w-100\">\r\n");
      out.write("                        <div class=\"row w-100\">\r\n");
      out.write("                            <div class=\"col-md-1\">\r\n");
      out.write("                                <div class=\"mdc-drawer__header\">\r\n");
      out.write("                                    <a href=\"index.html\" class=\"brand-logo\">\r\n");
      out.write("                                        <img src=\"assets/images/logo.png\" alt=\"logo\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-2 d-flex align-items-center\">\r\n");
      out.write("                                <h4 class=\"mb-0 header-title\">Quikue</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4 col-lg-3 align-items-left ms-auto\">\r\n");
      out.write("                                <div class=\"input-group d-flex align-items-center h-100\">\r\n");
      out.write("                                \r\n");
      out.write("                                    <select aria-label=\"Branch\" class=\"form-control form-select\" id=\"branch\" onchange=\"changeBranchCodeAndClearSubScreenData()\">\r\n");
      out.write("                                        <option value=\"S\">Select Branch</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-1 d-flex align-items-center\">\r\n");
      out.write("                    <div\r\n");
      out.write("                        class=\"mdc-top-app-bar__section mdc-top-app-bar__section--align-end mdc-top-app-bar__section-right\">\r\n");
      out.write("                        <div class=\"menu-button-container menu-profile d-none d-md-block\">\r\n");
      out.write("                            <button class=\"mdc-button mdc-menu-button\">\r\n");
      out.write("                                <span class=\"d-flex align-items-center\">\r\n");
      out.write("                                    <span class=\"figure\">\r\n");
      out.write("                                        <img src=\"assets/images/faces/face1.jpg\" alt=\"user\" class=\"user\">\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <div class=\"mdc-menu mdc-menu-surface\" tabindex=\"-1\">\r\n");
      out.write("                                <ul class=\"mdc-list\" role=\"menu\" aria-hidden=\"true\" aria-orientation=\"vertical\">\r\n");
      out.write("                                    <li class=\"mdc-list-item\" role=\"menuitem\">\r\n");
      out.write("                                        <div class=\"item-thumbnail item-thumbnail-icon-only\">\r\n");
      out.write("                                            <i class=\"mdi mdi-settings-outline text-primary\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div\r\n");
      out.write("                                            class=\"item-content d-flex align-items-start flex-column justify-content-center\">\r\n");
      out.write("                                            <h6 class=\"item-subject font-weight-normal\">Logout</h6>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!-- Construct Menu -->\r\n");
      out.write("		\r\n");
      out.write("		   <aside class=\"mdc-drawer mdc-drawer--dismissible\">\r\n");
      out.write("            <div class=\"mdc-drawer__content\">\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <button\r\n");
      out.write("                        class=\"material-icons mdc-top-app-bar__navigation-icon mdc-icon-button sidebar-toggler\">menu</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mdc-list-group\">\r\n");
      out.write("                    <nav class=\"mdc-list mdc-drawer-menu\" id=\"menu\">\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </aside>\r\n");
      out.write("\r\n");
      out.write("	<!-- Menu Construction completed -->\r\n");
      out.write("	<!-- Loading Area --->\r\n");
      out.write("	<div id=\"contiF\" class=\"main-wrapper mdc-drawer-app-content pt-2\">\r\n");
      out.write("			<input type='hidden' id='currentMenuId' value='0'/>\r\n");
      out.write("            <div class=\"container-fluid px-2\" id=\"bodyContainer\">\r\n");
      out.write("                \r\n");
      out.write("			</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Loading Area Completed--->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"errorContainer\" style='display:none;z-index:1001;' class=\"errorContainer\">\r\n");
      out.write("	<div id=\"error\" class=\"error\">\r\n");
      out.write("		<span class=\"errorContent\"><b id='error-message'> check </b><a id='errorClose' onclick='closeError()' class='close'><span class=\"ml-2 mdi mdi-close\"></span></a></span>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("<!-- <div class=\"modal\" tabindex=\"-1\" id=\"logoutmodal\" style=\"display: none;\">\r\n");
      out.write("	<div class=\"modal-dialog\">\r\n");
      out.write("	  <div class=\"modal-content\">\r\n");
      out.write("		<div class=\"modal-header\">\r\n");
      out.write("		  <h4 class=\"modal-title\">Logout</h4>\r\n");
      out.write("		  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"  onclick=\"logNo()\"></button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"modal-body\">\r\n");
      out.write("		  <h5>Do you want to exit the application?</h5>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"modal-footer\">\r\n");
      out.write("		  <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\" onclick=\"logNo()\">No</button>\r\n");
      out.write("		  <button type=\"button\" class=\"btn btn-primary\"  onclick=\"logYes()\">Yes</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("  </div> -->\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write("  loadBranchData(false);\r\n");
      out.write(" \r\n");
      out.write(" var ajaxObj=new FlexUI.Ajax();\r\n");
      out.write(" var menuData=ajaxObj.callAjax(\"GET\",\"/inventory/service/ajax\",\"ic=0&id=usermenu&login_id=");
      out.print(userId);
      out.write("\");\r\n");
      out.write("		function constructMenu(m){\r\n");
      out.write("			var menus=m.data;\r\n");
      out.write("			var s=menus.length;\r\n");
      out.write("			for(var i=0;i<s;i++){\r\n");
      out.write("				var menu=menus[i];\r\n");
      out.write("				if(menu[2]=='0'){\r\n");
      out.write("					var l=$('#menu').append(\"<div class='mdc-list-item mdc-drawer-item' id='main_\"+menu[0]+\"'><a class='mdc-drawer-link' href='#' menucap='\"+menu[1]+\"' menuid='\"+menu[0]+\"' menulink='\"+menu[3]+\"' data-toggle='expansionPanel'  data-target='submenu_\"+menu[1]+\"'><i class='\"+menu[4]+\" mdc-list-item__start-detail mdc-drawer-item-icon'></i><span>\"+menu[1]+\"</span></a><div class='mdc-expansion-panel' id='submenu_\"+menu[1]+\"'><nav class='mdc-list mdc-drawer-submenu' id='submenulist_\"+menu[0]+\"'></nav></div></div>\");\r\n");
      out.write("				}else{\r\n");
      out.write("					var ul=$('#submenulist_'+menu[2]);\r\n");
      out.write("					ul.append($(\"<div class='mdc-list-item mdc-drawer-item'><a class='mdc-drawer-link' href='#' menuid='\"+menu[0]+\"' onclick=\\\"menuClick(this,'\"+menu[3]+\"')\\\">\"+menu[1]+\"</a></div>\"));\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function changeBreadCrumb(l1,l2){\r\n");
      out.write("			$('#breadcrumbl1').html(l1);\r\n");
      out.write("			$('#breadcrumbl2').html(l2);\r\n");
      out.write("		}\r\n");
      out.write("		function menuClick(a,m){\r\n");
      out.write("			if(m!='#'){\r\n");
      out.write("				var mn=$(a).html();\r\n");
      out.write("				var pn=$(a).attr('pn');\r\n");
      out.write("				var menuId=$(a).attr('menuid');\r\n");
      out.write("				if(m!=null && m!=\"\" && m!=\"#\"){\r\n");
      out.write("					alert(m);\r\n");
      out.write("					if(menuId==1010001){\r\n");
      out.write("						if(window.confirm(\"Do you want to exit the application?\")){\r\n");
      out.write("							$(\"#bodyContainer\").html(\"\");\r\n");
      out.write("							$(\"#bodyContainer\").load(\"/inventory\"+m,onSuccess);\r\n");
      out.write("							$(\"#currentMenuId\").val(menuId);\r\n");
      out.write("						}\r\n");
      out.write("							// $(\"#logoutmodal\").show();\r\n");
      out.write("					}else if(menuId!=310005){\r\n");
      out.write("						$(\"#bodyContainer\").html(\"\");\r\n");
      out.write("						$(\"#bodyContainer\").load(\"/inventory\"+m,onSuccess);\r\n");
      out.write("						$(\"#currentMenuId\").val(menuId);\r\n");
      out.write("					}else{\r\n");
      out.write("						window.open(\"/inventory\"+m,\"touch\",\"fullscreen=yes,location=no,menubar=no,titlebar=no,toolbar=no\");\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				//showSideMenu(2);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		function logYes(){\r\n");
      out.write("						$(\"#bodyContainer\").html(\"\");\r\n");
      out.write("						$(\"#bodyContainer\").load(\"/inventory\"+m,onSuccess);\r\n");
      out.write("						$(\"#currentMenuId\").val(menuId);\r\n");
      out.write("		}\r\n");
      out.write("		function logNo(){\r\n");
      out.write("						$(\"#logoutmodal\").hide();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		constructMenu(menuData);\r\n");
      out.write("		\r\n");
      out.write("		var sourceLink='");
      out.print(src);
      out.write("';\r\n");
      out.write("		if(sourceLink!='' && sourceLink!=null){\r\n");
      out.write("			menuClick(sourceLink);\r\n");
      out.write("		}\r\n");
      out.write("		function onSuccess(){\r\n");
      out.write("			var menuId=$(\"#currentMenuId\").val();\r\n");
      out.write("			if(menuId!='1010001'){\r\n");
      out.write("				var actions=new FlexUI.Actions(menuId,'addGrp','saveGrp');\r\n");
      out.write("				actions.buildActions();\r\n");
      out.write("			}	\r\n");
      out.write("		}\r\n");
      out.write("		function closeError(){\r\n");
      out.write("			$(\"#errorContainer\").fadeOut();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function setErrorMessage(err){\r\n");
      out.write("		$(\"#error-message\").html(err);\r\n");
      out.write("		if(!$(\"#error\").is(\":visible\")){\r\n");
      out.write("			runEffect();\r\n");
      out.write("		}\r\n");
      out.write("		}\r\n");
      out.write("		  function runEffect() {\r\n");
      out.write("			$(\"#errorContainer\").show();\r\n");
      out.write("			var count = 5;\r\n");
      out.write("			countdown = setInterval(function(){\r\n");
      out.write("    				if (count ==0) {\r\n");
      out.write("      					clearInterval(countdown);\r\n");
      out.write("      					closeError();\r\n");
      out.write("    				}\r\n");
      out.write("    				count--;\r\n");
      out.write("  					}, 1000);\r\n");
      out.write("		  }\r\n");
      out.write("		  function showSideMenu(show){\r\n");
      out.write("			  if(show==1) {\r\n");
      out.write("					$('#sidBar').removeClass(\"sideBar2\");\r\n");
      out.write("				    $('#sidBar').addClass(\"\");\r\n");
      out.write("				    $('#leftbar').removeClass(\"sideBar sideBar2\");\r\n");
      out.write("				    $('#leftbar').addClass(\"sideBar\");\r\n");
      out.write("				    $('#contiF').removeClass(\"contiF2\");\r\n");
      out.write("				    $('#contiF').addClass(\"contiF\");\r\n");
      out.write("				    $('#leftbar1').css(\"display\",\"none\");\r\n");
      out.write("				    $('#leftbar').css(\"display\",\"block\");\r\n");
      out.write("			  }else{\r\n");
      out.write("			  		$('#sidBar').removeClass(\"sideBar2\");\r\n");
      out.write("				    $('#sidBar').addClass(\"sideBar2\");\r\n");
      out.write("				    $('#leftbar').removeClass(\"sideBar sideBar2\");\r\n");
      out.write("				    $('#leftbar').addClass(\"sideBar sideBar2\");\r\n");
      out.write("				    $('#contiF').removeClass(\"contiF2\");\r\n");
      out.write("				    $('#contiF').addClass(\"contiF2\");\r\n");
      out.write("	    			$('#leftbar1').css(\"display\",\"block\");\r\n");
      out.write("	    			$('#leftbar').css(\"display\",\"none\");\r\n");
      out.write("			  }\r\n");
      out.write("		  }		\r\n");
      out.write("		  function loadBranchData(){\r\n");
      out.write("				var ajaxObj=new FlexUI.Ajax();\r\n");
      out.write("				var bData=ajaxObj.callAjax(\"GET\",\"/inventory/service/ajax\",\"ic=0&id=userdefbranch,userbranch\");\r\n");
      out.write("				var branchData=bData.data.userbranch;\r\n");
      out.write("				var defBranchData=bData.data.userdefbranch;\r\n");
      out.write("				var branchCode=1;\r\n");
      out.write("				var branchName=0;\r\n");
      out.write("				var locationCode=6;\r\n");
      out.write("			$('#branch').children().remove();\r\n");
      out.write("			for(var i=0;i<branchData.length;i++){\r\n");
      out.write("				var brn=$(\"<option value='\"+branchData[i][branchCode]+\"'>\"+branchData[i][branchName]+\"</option>\");\r\n");
      out.write("				brn.data(\"location\",branchData[i][locationCode]);\r\n");
      out.write("				$('#branch').append(brn);\r\n");
      out.write("			}\r\n");
      out.write("			$('#branch').val(defBranchData[0][branchCode]);\r\n");
      out.write("}  		  \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
