/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.9
 * Generated at: 2024-01-31 07:53:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\" name=\"viewport\" content= \"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Products</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"card border-0 shadow\">\r\n");
      out.write("		<div class=\"card-body lpage\">\r\n");
      out.write("			<div class=\"row w-100\">\r\n");
      out.write("				<div class=\"col-md-6 d-flex align-items-center\">\r\n");
      out.write("					<h4 class=\"header-title\">Products</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div  class=\"col-md-6 text-right\" id=\"addGrp\"></div>\r\n");
      out.write("				<div  class=\"col-md-6 text-right\" id=\"saveGrp\" style='display:none'>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-edit\" onclick='onSaveClicked()'><span class=\"mdi mdi-check-circle-outline me-2\"></span>Save</button>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-clear mx-3\" onclick='hideMasterData()'><span class=\"mdi mdi-refresh me-2\"></span>Cancel</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"row w-100\" id=\"jqcontainer\" > <div class=\"table-container\"><div id=\"xyz\" class=\"w-100\"></div></div></div>	\r\n");
      out.write("			<div id=\"callback\" style=\"display:none\">\r\n");
      out.write("				<div class=\"table-container\">\r\n");
      out.write("					<div class=\"row w-100 ml-8\">  \r\n");
      out.write("						<div class=\"row w-100\"> \r\n");
      out.write("							<div id=\"group1\" class=\"row\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row w-100\"> \r\n");
      out.write("							<div id=\"inventory\" class=\"row\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row w-100\" style=\"display: none;\">\r\n");
      out.write("							<div id=\"taxconfig\" class=\"row w-100\" style=\"height:200px;\"> </div>					\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row w-100\">\r\n");
      out.write("							<div id=\"group2\" class=\"row\">\r\n");
      out.write("								<div class=\"subHe\">Product Image</div>\r\n");
      out.write("								<div id=\"d_imagepath\" class=\"form-group mbotto\">\r\n");
      out.write("									<div class=\"col-sm-9 mpRes\">\r\n");
      out.write("										<form id=\"uploadImage\" name=\"uploadImage\" action=\"/inventory/service/uploadimage\" method=\"POST\" enctype=\"multipart/form-data\" target=\"uploader_iframe\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-sm-6 mpRes\">\r\n");
      out.write("													<input type=\"file\" name=\"fileUpload\" id=\"fileUpload\"/>\r\n");
      out.write("													<input type=\"hidden\" name=\"groupid\" name=\"groupid\"/>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-sm-3 mpRes\">\r\n");
      out.write("													<button type=\"button\" class=\"btn btn-clear mx-3\"  onclick=\"saveDocuments()\"><span class=\"mdi mdi-filter-variant\">Upload Image</span></button>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</form>\r\n");
      out.write("										<iframe id=\"uploader_iframe\" name=\"uploader_iframe\" style=\"display: none;\"></iframe>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("					</div>\r\n");
      out.write("						<div class=\"row w-100\">\r\n");
      out.write("							<div id=\"taxinfo\" class=\"row w-100\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row w-100\">\r\n");
      out.write("							<div id=\"rackinfo\" class=\"row\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("<script>\r\n");
      out.write("  	var l=new FlexUI.Ajax();\r\n");
      out.write("    var sProps={title:{height:30,width:100,name:\"AMC\"},container:{id:\"callback\",isdialog:false},js:\"\",screen:[\r\n");
      out.write("  	{name:\"group1\",title:\"Product Details\",pcolumns:3,colcss:\"col-sm-4 col-md-4 col-lg-4\",height:40,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"beige\",contentType:\"Fields\",\r\n");
      out.write("  	fields:[{colno:1,name:\"code\",inputType:0,type:\"INT\",caption:\"Code\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"productname\"},\r\n");
      out.write("  	{colno:0,name:\"productname\",inputType:0,type:\"TEXT\",caption:\"Name\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"group\",\"validation\":\"validatespace\"},\r\n");
      out.write("  	{colno:1,name:\"group\",inputType:0,type:\"LOV\",caption:\"Group\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"manufacturer\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"productgroup\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"group\",tt:true,id:\"1\"},{tgt:\"group\",tt:false,id:\"0\"},{tgt:\"isserialized\",tt:false,id:\"2\"},{tgt:\"hasbatch\",tt:false,id:\"3\"},{tgt:\"hasexpiry\",tt:false,id:\"4\"},{tgt:\"isservice\",tt:false,id:\"5\"},{tgt:\"hasattribute\",tt:false,id:\"6\"}]}},\r\n");
      out.write("  	{colno:2,name:\"manufacturer\",inputType:0,type:\"LOV\",caption:\"Brand\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":30,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"maincategory\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"manufacturer\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"manufacturer\",tt:true,id:\"1\"},{tgt:\"manufacturer\",tt:false,id:\"0\"}]}},\r\n");
      out.write("  	{colno:2,name:\"imagepath\",inputType:0,type:\"TEXT\",caption:\"\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"mrp\"},\r\n");
      out.write("  	\r\n");
      out.write("  	{colno:0,name:\"maincategory\",inputType:0,type:\"LOV\",caption:\"Main Category\",mandatory:true,defaultValue:\"1\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":true,nf:\"subcategory1\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"maincategory\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"maincategory\",tt:true,id:\"1\"},{tgt:\"maincategory\",tt:false,id:\"0\"}]}},\r\n");
      out.write("  	{colno:1,name:\"subcategory1\",inputType:0,type:\"LOV\",caption:\"Sub Category11\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":true,nf:\"subcategory2\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"subcategory\",scrollEnabled:true,searchFromList:false,dsi:0,params:[{n:\"category\",src:\"maincategory\",ft:true}],results:[{tgt:\"subcategory1\",tt:true,id:\"1\"},{tgt:\"subcategory1\",tt:false,id:\"0\"}]}},\r\n");
      out.write("  	{colno:2,name:\"subcategory2\",inputType:0,type:\"LOV\",caption:\"Sub Category2\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":30,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":true,nf:\"generic\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"subcategory\",scrollEnabled:true,searchFromList:false,dsi:0,params:[{n:\"category\",src:\"subcategory1\",ft:true}],results:[{tgt:\"subcategory2\",tt:true,id:\"1\"},{tgt:\"subcategory2\",tt:false,id:\"0\"}]}},\r\n");
      out.write("  	\r\n");
      out.write("  	{colno:0,name:\"generic\",inputType:0,type:\"LOV\",caption:\"Generic\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":30,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"consumetype\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"generic\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"generic\",tt:true,id:\"1\"},{tgt:\"generic\",tt:false,id:\"0\"}]}},\r\n");
      out.write("  	{colno:1,name:\"consumetype\",inputType:0,type:\"LOV\",caption:\"Type\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":30,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"marketedby\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"consumetype\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"consumetype\",tt:true,id:\"1\"},{tgt:\"consumetype\",tt:false,id:\"0\"}]}},\r\n");
      out.write("  	{colno:2,name:\"marketedby\",inputType:0,type:\"LOV\",caption:\"Marketed By\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":30,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"unitgroup\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"manufacturer\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"marketedby\",tt:true,id:\"1\"},{tgt:\"marketedby\",tt:false,id:\"0\"}]}}\r\n");
      out.write("  	]},\r\n");
      out.write("  	{name:\"inventory\",title:\"Inventory Configuration\",pcolumns:3,colcss:\"col-sm-4 col-md-4 col-lg-4\",height:40,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"beige\",contentType:\"Fields\",\r\n");
      out.write("  	fields:[\r\n");
      out.write("	{colno:1,name:\"baseunit\",inputType:0,type:\"LOV\",caption:\"Base Unit\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"unitgroup\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"units\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[]}},\r\n");
      out.write("  	{colno:0,name:\"unitgroup\",inputType:0,type:\"LOV\",caption:\"Unit Group\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"purchaseunit\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"unitgroup\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"unitgroup\",tt:true,id:\"1\"},{tgt:\"unitgroup\",tt:false,id:\"0\"},{tgt:\"baseunit\",tt:false,id:\"2\"},{tgt:\"purchaseunit\",tt:true,id:\"2\"},{tgt:\"saleunit\",tt:true,id:\"2\"},{tgt:\"transferunit\",tt:true,id:\"2\"},{tgt:\"purchaseunit\",tt:false,id:\"3\"},{tgt:\"saleunit\",tt:false,id:\"3\"},{tgt:\"transferunit\",tt:false,id:\"3\"}]}},  \r\n");
      out.write("  	{colno:1,name:\"purchaseunit\",inputType:0,type:\"LOV\",caption:\"Purchase Unit\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"saleunit\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"units\",scrollEnabled:true,searchFromList:false,dsi:0,params:[{n:\"unitgroup\",src:\"unitgroup\",ft:true}],results:[]}},\r\n");
      out.write("  	{colno:2,name:\"saleunit\",inputType:0,type:\"LOV\",caption:\"Sales Unit\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"transferunit\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"units\",scrollEnabled:true,searchFromList:false,dsi:0,params:[{n:\"unitgroup\",src:\"unitgroup\",ft:true}],results:[]}},\r\n");
      out.write("  	{colno:0,name:\"transferunit\",inputType:0,type:\"LOV\",caption:\"Transfer Unit\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"inventorytype\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"units\",scrollEnabled:true,searchFromList:false,dsi:0,params:[{n:\"unitgroup\",src:\"unitgroup\",ft:true}],results:[]}},\r\n");
      out.write("  	{colno:1,name:\"inventorytype\",inputType:0,type:\"LOV\",caption:\"Inventory Type\",mandatory:false,defaultValue:\"1\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"purrate\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"inventorytypes\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"inventorytype\",tt:true,id:\"1\"},{tgt:\"inventorytype\",tt:false,id:\"0\"},{tgt:\"purchasable\",tt:false,id:\"2\"},{tgt:\"salable\",tt:false,id:\"3\"},{tgt:\"composite\",tt:false,id:\"4\"},{tgt:\"livestock\",tt:false,id:\"5\"},{tgt:\"isbulk\",tt:false,id:\"6\"},{tgt:\"costtype\",tt:false,id:\"7\"}]},\"validation\":\"validateInventoryType\"},\r\n");
      out.write("  	{colno:1,name:\"isserialized\",inputType:0,type:\"TEXT\",caption:\"Serialized?\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"isservice\"},\r\n");
      out.write("  	{colno:1,name:\"isservice\",inputType:0,type:\"TEXT\",caption:\"Service?\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"hasattribute\"},\r\n");
      out.write("  	{colno:1,name:\"hasattribute\",inputType:0,type:\"TEXT\",caption:\"Has Attributes\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":50,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"hasbatch\"},\r\n");
      out.write("  	{colno:0,name:\"hasbatch\",inputType:0,type:\"TEXT\",caption:\"Has Batch\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"hasexpiry\"},\r\n");
      out.write("  	{colno:1,name:\"hasexpiry\",inputType:0,type:\"TEXT\",caption:\"Has Expiry\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"selling\"},\r\n");
      out.write("  	{colno:1,name:\"purchasable\",inputType:0,type:\"TEXT\",caption:\"Purchasable?\",mandatory:false,defaultValue:\"1\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"isservice\"},\r\n");
      out.write("  	{colno:1,name:\"salable\",inputType:0,type:\"TEXT\",caption:\"Salable?\",mandatory:false,defaultValue:\"1\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"hasattribute\"},\r\n");
      out.write("  	{colno:1,name:\"composite\",inputType:0,type:\"TEXT\",caption:\"Composite\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":50,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"hasbatch\"},\r\n");
      out.write("  	{colno:0,name:\"livestock\",inputType:0,type:\"TEXT\",caption:\"Live Stock\",mandatory:false,defaultValue:\"1\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"hasexpiry\"},  	\r\n");
      out.write("    {colno:0,name:\"selling\",inputType:0,type:\"DECIMAL\",caption:\"Selling\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"mrp\"},\r\n");
      out.write("  	{colno:2,name:\"purrate\",inputType:0,type:\"DECIMAL\",caption:\"Purchase Rate\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"selling\"},\r\n");
      out.write("  	{colno:1,name:\"mrp\",inputType:0,type:\"DECIMAL\",caption:\"Mrp\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"offerhint\"},  	\r\n");
      out.write("  	{colno:1,name:\"offerhint\",inputType:0,type:\"TEXT\",caption:\"Offer Hint\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":25,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"allownegative\"},\r\n");
      out.write("  	{colno:2,name:\"allownegative\",inputType:1,type:\"TEXT\",caption:\"Allow Negative Stcok\",mandatory:true,defaultValue:\"\",\"textLength\":10,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"hasextras\",keys:\"Deny~Allow\",values:\"0~1\"},  	\r\n");
      out.write("	{colno:1,name:\"gkm\",inputType:0,type:\"DECIMAL\",caption:\"Margin\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"hasextras\"},\r\n");
      out.write("	{colno:0,name:\"hasextras\",inputType:1,type:\"TEXT\",caption:\"Has Extras\",mandatory:true,defaultValue:\"0\",\"textLength\":10,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"allowonline\",keys:\"No~Yes\",values:\"0~1\"},	\r\n");
      out.write("  	{colno:1,name:\"allowonline\",inputType:1,type:\"TEXT\",caption:\"Allow Online Selling\",mandatory:true,defaultValue:\"\",\"textLength\":10,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"bulkitem\",keys:\"Allow~Deny\",values:\"1~0\"},\r\n");
      out.write("  	{colno:2,name:\"bulkitem\",inputType:0,type:\"LOV\",caption:\"Bulk Item\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"status\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"bulkitems\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[]}},  	\r\n");
      out.write("	{colno:0,name:\"hsncode\",inputType:0,type:\"TEXT\",caption:\"HSN Code\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":30,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"status\"},\r\n");
      out.write("  	{colno:0,name:\"status\",inputType:1,type:\"TEXT\",caption:\"Status\",mandatory:true,defaultValue:\"\",\"textLength\":10,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"purtax\",keys:\"Active~InActive\",values:\"Active~InActive\"},\r\n");
      out.write("  	{colno:0,name:\"isbulk\",inputType:0,type:\"TEXT\",caption:\"Bulk Item\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"bulkitem\"},\r\n");
      out.write("  	{colno:0,name:\"costtype\",inputType:0,type:\"TEXT\",caption:\"Cost Type\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"bulkitem\"}\r\n");
      out.write("  	]},\r\n");
      out.write("  	\r\n");
      out.write("  	{name:\"taxconfig\",title:\"Tax Details\",height:30,width:98,minWidth:500,minHeight:200,colWidth:98,float:\"left\",backColor:\"biege\",contentType:\"Table\",tableProperties:{rowEmptyCheckColumn:1,optional:true,columns:[\r\n");
      out.write("    {order:\"0\",id: \"sno\", name: \"SNo\", field: \"sno\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":true,\"chkTag\":false,width:50,sno:true},\r\n");
      out.write("    {order:\"1\",id: \"location\", name: \"Branch\", field: \"location\",defaultValue:\"0\",\"inputType\":0,\"type\":\"LOV\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":true,width:200,\"chkTag\":true,lovOptions:{url:\"/inventory/service/ajax\",ajax:\"userbranch\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[]}},\r\n");
      out.write("    {order:\"2\",id: \"ptax\", name: \"PurchaseTax%\", field: \"ptax\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":99.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:150},\r\n");
      out.write("    {order:\"3\",id: \"pinclusive\", name: \"Inclusive\", field: \"pinclusive\",defaultValue:\"0\",\"inputType\":1,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:150,keys:\"No~Yes\",values:\"0~1\"},\r\n");
      out.write("    {order:\"4\",id: \"pservtax\", name: \"ServiceTax%\", field: \"pservtax\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:100},    \r\n");
      out.write("    {order:\"5\",id: \"stax\", name: \"SaleTax%\", field: \"stax\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":99.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:150},\r\n");
      out.write("    {order:\"6\",id: \"inclusive\", name: \"Inclusive\", field: \"inclusive\",defaultValue:\"0\",\"inputType\":1,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:150,keys:\"Yes~No\",values:\"1~0\"},\r\n");
      out.write("    {order:\"7\",id: \"servtax\", name: \"ServiceTax%\", field: \"servtax\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:100},\r\n");
      out.write("    {order:\"8\",id: \"minqty\", name: \"Min.Qty(in BaseUnit)\", field: \"minqty\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":9999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:150},\r\n");
      out.write("    {order:\"9\",id: \"maxqty\", name: \"Max.Qty(in BaseUnit)\", field: \"maxqty\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":9999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:150}\r\n");
      out.write("    ]}},\r\n");
      out.write("    \r\n");
      out.write("    {name:\"taxinfo\",title:\"Tax Configuration\",pcolumns:3,colcss:\"col-sm-4 col-md-4 col-lg-4\",height:40,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"beige\",contentType:\"Fields\",\r\n");
      out.write("  	fields:[\r\n");
      out.write("  	{colno:0,name:\"purtax\",inputType:0,type:\"DECIMAL\",caption:\"Purchase Tax\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"saltax\"},	\r\n");
      out.write("  	{colno:1,name:\"saltax\",inputType:0,type:\"DECIMAL\",caption:\"Sales Tax\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"isinclusive\"},  	\r\n");
      out.write("  	{colno:2,name:\"isinclusive\",inputType:1,type:\"TEXT\",caption:\"Tax Inclusive\",mandatory:true,defaultValue:\"\",\"textLength\":10,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"minimumqty\",keys:\"Yes~No\",values:\"1~0\"},  	\r\n");
      out.write("	{colno:0,name:\"minimumqty\",inputType:0,type:\"DECIMAL\",caption:\"Min.Qty(in BaseUnit)\",mandatory:false,defaultValue:\"0\",\"maxValue\":9999999.99,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"maximumqty\"},\r\n");
      out.write("	{colno:1,name:\"maximumqty\",inputType:0,type:\"DECIMAL\",caption:\"Max.Qty(in BaseUnit)\",mandatory:false,defaultValue:\"0\",\"maxValue\":9999999.99,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"rack\"}\r\n");
      out.write("  	]},\r\n");
      out.write("  	{name:\"rackinfo\",title:\"Rack Info\",pcolumns:3,colcss:\"col-sm-4 col-md-4 col-lg-4\",height:40,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"beige\",contentType:\"Fields\",\r\n");
      out.write("  	fields:[\r\n");
      out.write("  	{colno:0,name:\"rack\",inputType:0,type:\"TEXT\",caption:\"Rack\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"shelf\"},	\r\n");
      out.write("  	{colno:1,name:\"shelf\",inputType:0,type:\"TEXT\",caption:\"Shelf\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"box\"},  	\r\n");
      out.write("  	{colno:2,name:\"box\",inputType:0,type:\"TEXT\",caption:\"Box\",mandatory:false,defaultValue:\"\",\"textLength\":10,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"\"}  	\r\n");
      out.write("	\r\n");
      out.write("  	]}\r\n");
      out.write("  	]};\r\n");
      out.write("\r\n");
      out.write("	 \r\n");
      out.write("  var screenProps=changeScreenAttributes(110003,sProps);\r\n");
      out.write("  var product=new FlexUI.Screen(\"productmaster\",screenProps);\r\n");
      out.write("  jqReport(8,\"#xyz\");\r\n");
      out.write("  function addMasterData(){ \r\n");
      out.write("  	product.clearScreen(); \r\n");
      out.write("  	$('#callback').css('display','block');\r\n");
      out.write("  	$('#saveGrp').css('display','block');\r\n");
      out.write("  	$('#history').css('display','block');\r\n");
      out.write("  	$('#addGrp').css('display','none');\r\n");
      out.write("  	$('#xyz').css('display','none');\r\n");
      out.write("	$('#jqcontainer').css('display','none');\r\n");
      out.write("  	screenObjects.getScreenObject(\"productname\").focus();\r\n");
      out.write("  }\r\n");
      out.write("  function hideMasterData(){\r\n");
      out.write("  	$('#callback').css('display','none');\r\n");
      out.write("  	$('#saveGrp').css('display','none');\r\n");
      out.write("  	$('#history').css('display','none');\r\n");
      out.write("  	$('#addGrp').css('display','block');\r\n");
      out.write("  	$('#xyz').css('display','block');\r\n");
      out.write("	$('#jqcontainer').css('display','block');\r\n");
      out.write("  }  \r\n");
      out.write("  function toggleHeaderRow(){\r\n");
      out.write("  	toggleSearchToolBar(\"8\");\r\n");
      out.write("  }\r\n");
      out.write("  toggleHeaderRow();\r\n");
      out.write("  function onSaveClicked(id,me){\r\n");
      out.write("    var cid=screenObjects.getScreenObject(\"code\").getValue();\r\n");
      out.write("    if(cid!=\"0\" && cid!=\"\"){\r\n");
      out.write("    	product.setOperation(\"EDIT\");\r\n");
      out.write("    }\r\n");
      out.write("	var d=product.processDataToSave();\r\n");
      out.write("	if(\"FAILED\"!=d){\r\n");
      out.write("		var s=new FlexUI.Ajax();\r\n");
      out.write("		showLoader();\r\n");
      out.write("		var r=s.callAjax(\"POST\",\"/inventory/service/product\",d);\r\n");
      out.write("		hideLoader();\r\n");
      out.write("		if(r.result==\"Success\"){\r\n");
      out.write("			saveDocuments();\r\n");
      out.write("			setErrorMessage(r.message+\" [No:\"+r.code+\"]\");\r\n");
      out.write("			product.clearScreen();\r\n");
      out.write("			hideMasterData();\r\n");
      out.write("			reloadGrid(\"8\");\r\n");
      out.write("			return r.key;			\r\n");
      out.write("		}else{\r\n");
      out.write("			setErrorMessage(r.message);		\r\n");
      out.write("		}\r\n");
      out.write("		return 0;\r\n");
      out.write("	}\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function loadOrderData(url,code,did){\r\n");
      out.write("  	if(url==\"\"){\r\n");
      out.write("  		url=\"/inventory/service/product\";\r\n");
      out.write("  	}\r\n");
      out.write("  	if(code!=\"\"){\r\n");
      out.write("  		code=\"code=\"+code+\"\";\r\n");
      out.write("  	}\r\n");
      out.write("  	showLoader();\r\n");
      out.write("	var v=l.callAjax(\"GET\",url,code);\r\n");
      out.write("	product.clearScreen();\r\n");
      out.write("	product.loadData(v);\r\n");
      out.write("	screenObjects.getScreenObject('group').setEnabled(false);\r\n");
      out.write("	screenObjects.getScreenObject('inventorytype').setEnabled(false);\r\n");
      out.write("	screenObjects.getScreenObject('bulkitem').setEnabled(false);\r\n");
      out.write("	$('#callback').css('display','block');\r\n");
      out.write("  	$('#saveGrp').css('display','block');\r\n");
      out.write("  	$('#history').css('display','block');\r\n");
      out.write("  	$('#addGrp').css('display','none');\r\n");
      out.write("  	$('#xyz').css('display','none');\r\n");
      out.write("	$('#jqcontainer').css('display','none');\r\n");
      out.write("  	hideLoader();\r\n");
      out.write("  	screenObjects.getScreenObject(\"productname\").focus();\r\n");
      out.write("  }\r\n");
      out.write("  function validateInventoryType(id,me){\r\n");
      out.write("  	if(screenObjects.getScreenObject('isbulk').getValue()==1){\r\n");
      out.write("  		screenObjects.getScreenObject('bulkitem').setEnabled(false);\r\n");
      out.write("  	}else{\r\n");
      out.write("  		screenObjects.getScreenObject('bulkitem').setEnabled(true);\r\n");
      out.write("  	}\r\n");
      out.write("	return true;  \r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  function validatespace(){\r\n");
      out.write("		$(\"#productname\").val($(\"#productname\").val().trim());\r\n");
      out.write("	    return true;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /*$(document).ready(function()\r\n");
      out.write("	{  \r\n");
      out.write("        $('#uploadImage').ajaxForm({\r\n");
      out.write("	        success: function(data) {\r\n");
      out.write("	        	hideLoader();\r\n");
      out.write("        		if (data==\"File uploaded\"){\r\n");
      out.write("        		\r\n");
      out.write("				}\r\n");
      out.write("        	}\r\n");
      out.write("    	});\r\n");
      out.write("	})*/ \r\n");
      out.write("	\r\n");
      out.write("	$('#uploadImage').submit(function (e) {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        var fd = new FormData($(this)[0]);\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: '/inventory/service/uploadimage',\r\n");
      out.write("            data: fd,\r\n");
      out.write("            processData: false,\r\n");
      out.write("            contentType: false,\r\n");
      out.write("            type: 'POST',\r\n");
      out.write("            success: function(data){\r\n");
      out.write("            var r=JSON.parse(data);\r\n");
      out.write("            	hideLoader();\r\n");
      out.write("            	setErrorMessage(r.message,1);\r\n");
      out.write("        		if (r.result==\"Success\"){\r\n");
      out.write("        			screenObjects.getScreenObject(\"imagepath\").setValue(r.path);\r\n");
      out.write("				}\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("});\r\n");
      out.write("   \r\n");
      out.write("function saveDocuments(){\r\n");
      out.write("	var importFileName=$.trim($(\"#fileUpload\").val());\r\n");
      out.write("	/*var group=$.trim($(\"#group\").val());\r\n");
      out.write("	if(group==null || group==\"\"){\r\n");
      out.write("		setErrorMessage(\"Please Select Product Group\",1);\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	$('#groupid').val(group);*/\r\n");
      out.write("	if(importFileName.indexOf(\"\\\\\")){\r\n");
      out.write("		importFileName=importFileName.substr(importFileName.lastIndexOf('\\\\')+1);\r\n");
      out.write("	}	\r\n");
      out.write("	var ext=importFileName.substr(importFileName.lastIndexOf('.')+1).toLowerCase();\r\n");
      out.write("	if(ext=='png' || ext=='jpeg'|| ext=='jpg'){\r\n");
      out.write("		showLoader();\r\n");
      out.write("		$(\"#uploadImage\").submit();\r\n");
      out.write("	}else{\r\n");
      out.write("		setErrorMessage(\"Please upload png/jpg format only\",1);	\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("	\r\n");
      out.write("</script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
