/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.9
 * Generated at: 2023-08-21 05:30:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class screenAttributes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("  <title>Screen</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"width:100%;float:left\">\r\n");
      out.write("<div id=\"callback\" style=\"display:block\" >\r\n");
      out.write("<div class=\"col-md-12\">\r\n");
      out.write("	<label>Name:</label> <input type=\"text\" id=\"screenname\"/>\r\n");
      out.write("	<label>Screencode:</label> <input type=\"text\" id=\"screencode\"/>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-12\">\r\n");
      out.write("	<textarea col=200 row=100 id=\"screenprop\">\r\n");
      out.write("	</textarea>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clearfix\"></div>   \r\n");
      out.write("<div id=\"saveGrp\" style='display:block' class=\"mTBx\">\r\n");
      out.write("<span>\r\n");
      out.write("<button type=\"button\" class=\"btn btn-primary mRhAj\" onclick='onSaveClicked()'>Save</button>\r\n");
      out.write("<button type=\"button\" class=\"btn btn-default\" onclick='hideMasterData()'>Cancel</button>\r\n");
      out.write("</span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var showExpiry=false;\r\n");
      out.write("var ew=0;\r\n");
      out.write("var cKeys=\"All\";\r\n");
      out.write("var cValues=\"0\";\r\n");
      out.write("\r\n");
      out.write("//\"screencode\":\"310001\",\"screenname\":\"\",\"screentitle\":\"\",\r\n");
      out.write("var sProps={\"screencode\":\"310001\",\"screenname\":\"Sales\",\"screentitle\":\"Sales\",title:{height:25,width:100,name:\"Invoice\"},container:{id:\"callback\",isdialog:false},js:\"js/validations/invoice.js\",screen:[\r\n");
      out.write("  {name:\"group1\",title:\"\",pcolumns:0,height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[{colno:0,name:\"code\",inputType:0,type:\"INT\",caption:\"Code\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"branch\"},\r\n");
      out.write("  {colno:0,name:\"name\",inputType:0,type:\"TEXT\",caption:\"Name\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"branch\"},\r\n");
      out.write("  {colno:0,name:\"mobile\",inputType:0,type:\"TEXT\",caption:\"Mobile\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":30,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"billdate\",validation:\"fetchCustomer\"},  \r\n");
      out.write("  {colno:0,name:\"custtype\",inputType:1,type:\"TEXT\",caption:\"Type\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"custname\",keys:cKeys,values:cValues,onchange:\"validateCustType\"},\r\n");
      out.write("  {colno:0,name:\"custalias\",inputType:0,type:\"LOV\",caption:\"Alias\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":true,nf:\"billdate\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"customer\",scrollEnabled:true,searchFromList:false,dsi:8,params:[{n:\"custtype\",src:\"custtype\",ft:false}],results:[{tgt:\"custname\",tt:true,id:\"0\"},{tgt:\"name\",tt:false,id:\"1\"},{tgt:\"custname\",tt:false,id:\"1\"},{tgt:\"mobile\",tt:false,id:\"2\"},{tgt:\"address\",tt:false,id:\"3,4,5,6\",m:true},{tgt:\"address1\",tt:false,id:\"3\"},{tgt:\"address2\",tt:false,id:\"4\"},{tgt:\"city\",tt:false,id:\"5\"},{tgt:\"pincode\",tt:false,id:\"6\"},{tgt:\"creditdays\",tt:false,id:\"7\"},{tgt:\"showcreditdays\",tt:false,id:\"7\"},{tgt:\"custalias\",tt:false,id:\"8\"},{tgt:\"custalias\",tt:true,id:\"8\"}]}},\r\n");
      out.write("  {colno:0,name:\"custname\",inputType:0,type:\"LOV\",caption:\"Name\",mandatory:true,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"billdate\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"customer\",scrollEnabled:true,searchFromList:false,dsi:2,params:[{n:\"custtype\",src:\"custtype\",ft:false}],results:[{tgt:\"custname\",tt:true,id:\"0\"},{tgt:\"name\",tt:false,id:\"1\"},{tgt:\"custname\",tt:false,id:\"1\"},{tgt:\"mobile\",tt:false,id:\"2\"},{tgt:\"address\",tt:false,id:\"3,4,5,6\",m:true},{tgt:\"address1\",tt:false,id:\"3\"},{tgt:\"address2\",tt:false,id:\"4\"},{tgt:\"city\",tt:false,id:\"5\"},{tgt:\"pincode\",tt:false,id:\"6\"},{tgt:\"creditdays\",tt:false,id:\"7\"},{tgt:\"showcreditdays\",tt:false,id:\"7\"},{tgt:\"custalias\",tt:false,id:\"8\"}]}},\r\n");
      out.write("  {colno:0,name:\"address\",inputType:4,type:\"SPAN\",caption:\"Address\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"chkTag\":false,nf:\"address2\"},  \r\n");
      out.write("  {colno:0,name:\"address1\",inputType:0,type:\"TEXT\",caption:\"Building\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"address2\"},\r\n");
      out.write("  {colno:0,name:\"address2\",inputType:0,type:\"TEXT\",caption:\"Street\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":100,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"city\"},\r\n");
      out.write("  {colno:0,name:\"city\",inputType:0,type:\"TEXT\",caption:\"City\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":50,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"pincode\"},\r\n");
      out.write("  {colno:0,name:\"pincode\",inputType:0,type:\"TEXT\",caption:\"PinCode\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"billdate\"},\r\n");
      out.write("  {colno:0,name:\"creditdays\",inputType:0,type:\"INT\",caption:\"Credit Days\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"salesman\"},\r\n");
      out.write("  {colno:0,name:\"showcreditdays\",inputType:4,type:\"INT\",caption:\"Credit\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"salesman\"}\r\n");
      out.write("  ]},\r\n");
      out.write("  {name:\"branch\",title:\"\",pcolumns:0,height:30,width:98,minWidth:500,minHeight:200,colWidth:45,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[ {colno:0,name:\"branch\",inputType:0,type:\"LOV\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"location\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"userbranch\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"branch\",tt:true,id:\"1\"},{tgt:\"branch\",tt:false,id:\"0\"},{tgt:\"location\",tt:false,id:\"5\"},{tgt:\"location\",tt:true,id:\"6\"}]}},\r\n");
      out.write("  {colno:0,name:\"location\",inputType:0,type:\"LOV\",caption:\"\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":true,nf:\"custname\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"branchlocations\",scrollEnabled:true,searchFromList:false,dsi:0,params:[{n:\"branch\",src:\"branch\",ft:true}],results:[]}}\r\n");
      out.write("  ]},\r\n");
      out.write("    {name:\"group2\",title:\"\",pcolumns:0,height:30,width:98,minWidth:500,minHeight:200,colWidth:33,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"billtype\",inputType:1,type:\"TEXT\",caption:\"Bill Type\",keys:\"Cash~Credit~Credit Card~Coupon~Cheque~Split\",values:\"CA~CR~CC~CO~CQ~SP\",defaultValue:\"C\",\"readOnly\":false,\"chkTag\":false,nf:\"billdate\",visible:false},\r\n");
      out.write("  {colno:0,name:\"billno\",inputType:0,type:\"INT\",caption:\"Bill No\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"billdate\"},\r\n");
      out.write("  {colno:0,name:\"showbillno\",inputType:4,type:\"INT\",caption:\"Bill No\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"chkTag\":false,nf:\"billdate\"},\r\n");
      out.write("  {colno:0,name:\"billdate\",inputType:0,type:\"DATE\",caption:\"Bill Date\",format:\"dd/mm/yyyy\",defaultValue:\"\",\"chkTag\":false,visible:true,nf:\"salesman\"},\r\n");
      out.write("  {colno:0,name:\"salesman\",inputType:0,type:\"LOV\",caption:\"Salesman\",mandatory:false,defaultValue:\"\",\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"invoice_data\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"employee\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"salesman\",tt:false,id:\"0\"},{tgt:\"salesman\",tt:true,id:\"1\"},{tgt:\"empid\",tt:false,id:\"2\"}]}},\r\n");
      out.write("  {colno:0,name:\"empid\",inputType:0,type:\"INT\",caption:\"EmpId\",mandatory:false,defaultValue:\"0\",\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"\"},\r\n");
      out.write("  {colno:0,name:\"professional\",inputType:0,type:\"LOV\",caption:\"Professional\",mandatory:false,defaultValue:\"\",\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"invoice_data\",lovOptions:{url:\"/inventory/service/ajax\",ajax:\"employee\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[{tgt:\"professional\",tt:false,id:\"0\"},{tgt:\"professional\",tt:true,id:\"2\"},{tgt:\"prfcode\",tt:true,id:\"2\"}]}},\r\n");
      out.write("  {colno:0,name:\"prfcode\",inputType:0,type:\"INT\",caption:\"Prfcode\",mandatory:false,defaultValue:\"0\",\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"\"}  \r\n");
      out.write("  ]},\r\n");
      out.write("  {name:\"billdetail\",title:\"\",pcolumns:0,height:30,width:98,minWidth:500,minHeight:200,colWidth:33,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"dcno\",inputType:0,type:\"INT\",caption:\"DC No\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"dcdate\"},\r\n");
      out.write("  {colno:0,name:\"dcdate\",inputType:0,type:\"DATE\",caption:\"DC Date\",format:\"dd/mm/yyyy\",defaultValue:\"\",\"chkTag\":false,visible:false,nf:\"ordertype\"},\r\n");
      out.write("  {colno:0,name:\"ordertype\",inputType:1,type:\"TEXT\",caption:\"Order Type\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"sono\",keys:\"Direct Sale~Sales Order\",values:\"DS~SO\",defaultValue:\"SE\"},\r\n");
      out.write("  {colno:0,name:\"sono\",inputType:0,type:\"INT\",caption:\"SO No\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"sodate\"},\r\n");
      out.write("  {colno:0,name:\"sosno\",inputType:0,type:\"INT\",caption:\"SO No\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"sodate\"},\r\n");
      out.write("  {colno:0,name:\"sodate\",inputType:0,type:\"DATE\",caption:\"SO Date\",format:\"dd/mm/yyyy\",defaultValue:\"\",\"chkTag\":false,visible:false,nf:\"despthro\"}  ,\r\n");
      out.write("  {colno:0,name:\"showordertype\",inputType:4,type:\"TEXT\",caption:\"Order Type\",value:\"Direct Sale\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"sono\",keys:\"Direct Sale~Sales Order\",values:\"DS~SO\",defaultValue:\"SE\"},\r\n");
      out.write("  {colno:0,name:\"showsono\",inputType:4,type:\"INT\",caption:\"SO No\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"chkTag\":false,nf:\"sodate\"},\r\n");
      out.write("  {colno:0,name:\"showsodate\",inputType:4,type:\"DATE\",caption:\"SO Date\",format:\"dd/mm/yyyy\",defaultValue:\"\",\"chkTag\":false,visible:true,nf:\"despthro\"}\r\n");
      out.write("  ]},{name:\"dummyDiv\",title:\"\",pcolumns:0,height:30,width:98,minWidth:500,minHeight:200,colWidth:33,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {name:\"dummy1\",inputType:4,type:\"TEXT\",caption:\"\",keys:\"Cash~Cheque\",values:\"C~Q\",defaultValue:\"C\",\"readOnly\":false,\"chkTag\":false,nf:\"documents\",visible:true},\r\n");
      out.write("  {name:\"dummy2\",inputType:4,type:\"TEXT\",caption:\"\",keys:\"Cash~Cheque\",values:\"C~Q\",defaultValue:\"C\",\"readOnly\":false,\"chkTag\":false,nf:\"documents\",visible:true},\r\n");
      out.write("  {name:\"dummy3\",inputType:4,type:\"TEXT\",caption:\"\",keys:\"Cash~Cheque\",values:\"C~Q\",defaultValue:\"C\",\"readOnly\":false,\"chkTag\":false,nf:\"documents\",visible:true}\r\n");
      out.write("  ]},\r\n");
      out.write("  {name:\"dummyDiv1\",title:\"\",pcolumns:0,height:30,width:98,minWidth:500,minHeight:200,colWidth:33,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {name:\"dummy4\",inputType:4,type:\"TEXT\",caption:\"\",keys:\"Cash~Cheque\",values:\"C~Q\",defaultValue:\"C\",\"readOnly\":false,\"chkTag\":false,nf:\"documents\",visible:true},\r\n");
      out.write("  {name:\"dummy5\",inputType:4,type:\"TEXT\",caption:\"\",keys:\"Cash~Cheque\",values:\"C~Q\",defaultValue:\"C\",\"readOnly\":false,\"chkTag\":false,nf:\"documents\",visible:true},\r\n");
      out.write("  {name:\"dummy6\",inputType:4,type:\"TEXT\",caption:\"\",keys:\"Cash~Cheque\",values:\"C~Q\",defaultValue:\"C\",\"readOnly\":false,\"chkTag\":false,nf:\"documents\",visible:true}\r\n");
      out.write("  ]},\r\n");
      out.write("  {name:\"transport\",title:\"\",pcolumns:0,height:30,width:98,minWidth:500,minHeight:200,colWidth:33,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"despthro\",inputType:0,type:\"LOV\",caption:\"Transport\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"pf\",colspan:2,lovOptions:{url:\"/inventory/service/ajax\",ajax:\"transport\",scrollEnabled:true,searchFromList:false,dsi:0,params:[],results:[]}},\r\n");
      out.write("  {colno:0,name:\"documents\",inputType:0,type:\"TEXT\",caption:\"Documents\",mandatory:false,defaultValue:\"\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"paymode\"},\r\n");
      out.write("  {colno:0,name:\"paymode\",inputType:1,type:\"TEXT\",caption:\"Payment Mode\",keys:\"Cash~Cheque\",values:\"C~Q\",defaultValue:\"C\",\"readOnly\":false,\"chkTag\":false,nf:\"lrno\",visible:false},\r\n");
      out.write("  {colno:0,name:\"pf\",inputType:0,type:\"DECIMAL\",caption:\"Packing\",mandatory:false,defaultValue:\"0\",\"maxValue\":99999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"discount\",colspan:2,onchange:\"onTaxChange\"},\r\n");
      out.write("  {colno:0,name:\"cdisc\",inputType:0,type:\"DECIMAL\",caption:\"Cash DiscPerc\",mandatory:false,defaultValue:\"0\",\"maxValue\":99.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"invoice_data\",colspan:2,onchange:\"\"},\r\n");
      out.write("  {colno:0,name:\"cdiscamt\",inputType:0,type:\"DECIMAL\",caption:\"Cash Disc Amt\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":false,\"readOnly\":false,\"chkTag\":false,nf:\"invoice_data\",colspan:2,onchange:\"\"}\r\n");
      out.write("  ]},\r\n");
      out.write("  {name:\"lrdet\",title:\"\",pcolumns:0,height:30,width:98,minWidth:500,minHeight:200,colWidth:33,float:\"left\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[\r\n");
      out.write("  {colno:0,name:\"lrno\",inputType:0,type:\"TEXT\",caption:\"LR No\",mandatory:false,defaultValue:\"NA\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"chkTag\":false,nf:\"lrdate\"},\r\n");
      out.write("  {colno:0,name:\"lrdate\",inputType:0,type:\"DATE\",caption:\"LR Date\",format:\"dd/mm/yyyy\",defaultValue:\"\",\"chkTag\":false,visible:true,nf:\"creditdays\"},\r\n");
      out.write("  {colno:0,name:\"go\",inputType:3,type:\"\",caption:\"Go\",onclick:\"calculateCashDiscount\",visible:true}\r\n");
      out.write("  ]},\r\n");
      out.write("  {name:\"invoice\",title:\"Products\",height:30,width:98,minWidth:500,minHeight:250,colWidth:50,float:\"left\",backColor:\"biege\",contentType:\"Table\",tableProperties:{rowEmptyCheckColumn:1,columns:[\r\n");
      out.write("    {order:\"0\",id: \"sno\", name: \"SNo\", field: \"sno\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":true,\"chkTag\":false,width:50,sno:true},\r\n");
      out.write("    {order:\"1\",id: \"product\", name: \"Product\", field: \"product\",defaultValue:\"0\",\"inputType\":0,\"type\":\"LOV\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":true,lovOptions:{url:\"/inventory/service/ajax\",ajax:\"saleproduct\",scrollEnabled:true,searchFromList:false,dsi:0,params:[{n:\"branch\",src:\"branch\",ft:true}],results:[\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"1\",id:\"0\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:true,row:\"cr\",col:\"1\",id:\"1\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"2\",id:\"2\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"23\",id:\"5\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"30\",id:\"7\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"6\",id:\"8\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"7\",id:\"10\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"8\",id:\"12\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"14\",id:\"10\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"15\",id:\"12\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"36\",id:\"13\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"16\",id:\"14\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"38\",id:\"15\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"25\",id:\"16\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"3\",id:\"17\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"4\",id:\"18\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"39\",id:\"19\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"40\",id:\"20\"}        \r\n");
      out.write("        \r\n");
      out.write("    ]},width:200,chkTag:true,prevalidate:\"checkBarCode\",validation:\"getAttributeDetail\"},\r\n");
      out.write("    {order:\"2\",id: \"pgcode\", name: \"pgcode\", field: \"pgcode\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0},\r\n");
      out.write("    {order:\"3\",id: \"serialized\", name: \"serialized\", field: \"serialized\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0},\r\n");
      out.write("    {order:\"4\",id: \"isattribute\", name: \"isattribute\", field: \"isattribute\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0},\r\n");
      out.write("    {order:\"5\",id: \"attribid\", name: \"AttributeId\", field: \"attribid\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},        \r\n");
      out.write("    {order:\"6\",id: \"unitgroup\", name: \"UnitGroup\", field: \"unitgroup\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0},\r\n");
      out.write("    {order:\"7\",id: \"unitname\", name: \"Units\", field: \"unitname\",defaultValue:\"0\",\"inputType\":0,\"type\":\"LOV\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":true,lovOptions:{url:\"/inventory/service/ajax\",ajax:\"units\",scrollEnabled:true,searchFromList:false,dsi:0,params:[{n:\"unitgroup\",src:\"invoice_data\",row:\"cr\",col:\"6\",ft:false}],results:[\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"7\",id:\"0\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"8\",id:\"1\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"14\",id:\"0\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"15\",id:\"1\"},\r\n");
      out.write("    {tgt:\"invoice_data\",tt:false,row:\"cr\",col:\"36\",id:\"2\"}\r\n");
      out.write("    ]},width:80,chkTag:false,validation:\"\"},\r\n");
      out.write("    {order:\"8\",id: \"unitid\", name: \"unitid\", field: \"unitid\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0},\r\n");
      out.write("    {order:\"9\",id: \"batchno\", name: \"BatchNo\", field: \"batchno\",defaultValue:\"NA\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":showExpiry,\"readOnly\":true,\"mandatory\":showExpiry,width:ew,chkTag:false},\r\n");
      out.write("    {order:\"10\",id: \"batchdt\", name: \"BatchDt\", field: \"batchdt\",defaultValue:\"NA\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"11\",id: \"expdt\", name: \"ExpDt\", field: \"expdt\",defaultValue:\"\",\"inputType\":0,\"type\":\"DATE\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":showExpiry,\"readOnly\":true,\"mandatory\":showExpiry,width:ew,chkTag:false},\r\n");
      out.write("    {order:\"12\",id: \"qty\", name: \"Qty\", field: \"quantity\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":true,width:100,onchange:\"onRateQuantityChange\",cTotal:true,validation:\"validateStock\"},\r\n");
      out.write("    {order:\"13\",id: \"freeqty\", name: \"Free\", field: \"freeqty\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:80,onchange:\"onRateQuantityChange\",cTotal:true,validation:\"getSerialDetail\"},\r\n");
      out.write("    {order:\"14\",id: \"funitname\", name: \"Units\", field: \"funitname\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"mandatory\":true,width:0,chkTag:false},\r\n");
      out.write("    {order:\"15\",id: \"funitid\", name: \"unitid\", field: \"funitid\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0},                    \r\n");
      out.write("    {order:\"16\",id: \"unit\", name: \"Unit\", field: \"unit\",defaultValue:\"1\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},    \r\n");
      out.write("    {order:\"17\",id: \"stock\", name: \"Stock\", field: \"stock\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"18\",id: \"rate\", name: \"Rate\", field: \"rate\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":true,width:100,onchange:\"onRateQuantityChange\",align:\"right\"},\r\n");
      out.write("    {order:\"19\",id: \"discperc\", name: \"DiscPerc\", field: \"discperc\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":99.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:100,onchange:\"onRateQuantityChange\",align:\"right\"},\r\n");
      out.write("	{order:\"20\",id: \"discamt\", name: \"Disc Amt\", field: \"discamt\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:100,align:\"right\"},\r\n");
      out.write("    {order:\"21\",id: \"cashdiscperc\", name: \"Cash DiscPerc\", field: \"cashdiscperc\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":false,\"readOnly\":false,\"mandatory\":false,width:0,onchange:\"onRateQuantityChange\",align:\"right\"},\r\n");
      out.write("	{order:\"22\",id: \"cashdiscamt\", name: \"Cash Disc Amount\", field: \"cashdiscamt\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":false,\"readOnly\":false,\"mandatory\":false,width:0,align:\"right\"},	\r\n");
      out.write("    {order:\"23\",id: \"staxperc\", name: \"S.TaxPerc\", field: \"staxperc\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:100,onchange:\"onRateQuantityChange\",align:\"right\"},\r\n");
      out.write("	{order:\"24\",id: \"staxamt\", name: \"S.Tax Amt\", field: \"staxamt\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:100,align:\"right\"},\r\n");
      out.write("	{order:\"25\",id: \"srtax\", name: \"Service TaxPerc\", field: \"srtaxperc\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":false,\"mandatory\":false,width:100,onchange:\"onRateQuantityChange\",align:\"right\"},\r\n");
      out.write("	{order:\"26\",id: \"srtaxamt\", name: \"Service Tax Amount\", field: \"srtaxamt\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:100,align:\"right\"},		\r\n");
      out.write("    {order:\"27\",id: \"amount\", name: \"Amount\", field: \"amount\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":true,width:150,cTotal:true,align:\"right\"},\r\n");
      out.write("    {order:\"28\",id: \"netamount\", name: \"NetAmount\", field: \"netamount\",defaultValue:\"y\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"mandatory\":true,width:150,cTotal:true,align:\"right\"},\r\n");
      out.write("    {order:\"29\",id: \"csdid\", name: \"CsdId\", field: \"csdid\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"30\",id: \"taxincl\", name: \"TaxInclu\", field: \"taxincl\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"31\",id: \"taxableamt\", name: \"TaxableAmt\", field: \"taxableamt\",defaultValue:\"0\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":true,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"32\",id: \"impno\", name: \"impno\", field: \"impno\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"33\",id: \"impsno\", name: \"impsno\", field: \"impsno\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"34\",id: \"imptype\", name: \"imptype\", field: \"imptype\",defaultValue:\"NA\",\"inputType\":0,\"type\":\"TEXT\",\"maxValue\":0,\"textLength\":2,\"decimalLength\":0,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"35\",id: \"selling\", name: \"selling\", field: \"selling\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":999999.99,\"textLength\":10,\"decimalLength\":2,\"visible\":false,\"readOnly\":false,\"mandatory\":false,width:0,align:\"right\"},\r\n");
      out.write("    {order:\"36\",id: \"conversionvalue\", name: \"conversionvalue\", field: \"conversionvalue\",defaultValue:\"0\",\"inputType\":0,\"type\":\"DECIMAL\",\"maxValue\":0,\"textLength\":20,\"decimalLength\":10,\"visible\":false,\"readOnly\":true,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"37\",id: \"basequantity\", name: \"BaseQuantity\", field: \"basequantity\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"38\",id: \"allownegative\", name: \"AllowNegative\", field: \"allownegative\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"39\",id: \"composite\", name: \"Composite\", field: \"composite\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"mandatory\":false,width:0,chkTag:false},\r\n");
      out.write("    {order:\"40\",id: \"updatestock\", name: \"UpdateStock\", field: \"updatestock\",defaultValue:\"0\",\"inputType\":0,\"type\":\"INT\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":0,\"visible\":false,\"readOnly\":false,\"mandatory\":false,width:0,chkTag:false}\r\n");
      out.write("    ]}},\r\n");
      out.write("  {name:\"group3\",height:20,width:45,minWidth:250,minHeight:50,colWidth:98,float:\"right\",backColor:\"biege\",contentType:\"Fields\",\r\n");
      out.write("  fields:[  {name:\"discamt\",inputType:0,type:\"DECIMAL\",caption:\"Total Discount\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"chkTag\":false,nf:\"taxamt\",onchange:\"onTaxChange\"},\r\n");
      out.write("  {name:\"taxamt\",inputType:0,type:\"DECIMAL\",caption:\"VAT\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"chkTag\":false,nf:\"total\"},\r\n");
      out.write("  {name:\"servtaxamt\",inputType:0,type:\"DECIMAL\",caption:\"Service Tax\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":false,\"readOnly\":true,\"chkTag\":false,nf:\"pf\",onchange:\"onTaxChange\"},\r\n");
      out.write("  {name:\"total\",inputType:0,type:\"DECIMAL\",caption:\"Total:\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"chkTag\":false,nf:\"totalamt\"},    \r\n");
      out.write("  {name:\"totalamt\",inputType:0,type:\"DECIMAL\",caption:\"Net Amount\",mandatory:true,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":true,\"readOnly\":true,\"chkTag\":false},\r\n");
      out.write("  {name:\"advanceamt\",inputType:0,type:\"DECIMAL\",caption:\"Advance Amount\",mandatory:false,defaultValue:\"0\",\"maxValue\":0,\"textLength\":10,\"decimalLength\":2,\"visible\":false,\"readOnly\":true,\"chkTag\":false}\r\n");
      out.write("  ]\r\n");
      out.write("  }]};\r\n");
      out.write("  function onSaveClicked(id,me){\r\n");
      out.write("  \r\n");
      out.write("	var s=new FlexUI.Ajax();\r\n");
      out.write("	var d='data={\"savedata\":'+JSON.stringify(sProps)+\"}\";\r\n");
      out.write("	alert(sProps);\r\n");
      out.write("	var r=s.callAjax(\"POST\",\"/inventory/service/screenattributes\",d);\r\n");
      out.write("	if(r.result==\"Success\"){\r\n");
      out.write("		setErrorMessage(r.message+\" [No:\"+r.code+\"]\");\r\n");
      out.write("	}else{\r\n");
      out.write("		setErrorMessage(r.message);		\r\n");
      out.write("	}\r\n");
      out.write("	return 0;\r\n");
      out.write("  }  \r\n");
      out.write("</script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
